---
title: "PTB GAM stratified by maternal nationality, SSEP or Language Region"
author: "Mathilde Le Vu"
date:  "`r Sys.Date()`"
html_document: 
output:
  rmdformats::robobook:
    code_folding: show
    self_contained: true
    highlight: pygments
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Socio economic position : stratification
## SSEP by tertile
```{r include=FALSE}
m_PTB_bam_L_SSEP1 <- bam(PTB ~ s(BW) + s(mat_age) + s(birth_Y_M_num) + s(month, bs="cc") + s(mean_Alt_mean2)+ parity_cat + sex + Urban3 + Language + mother_nationality_cat2  + civil_status3 + HW + GR + COVID_first_wave + COVID_second_wave, family="binomial", data=bevn_eco_in7_L_SSEP1)  
m_PTB_bam_M_SSEP1 <- bam(PTB ~ s(BW) + s(mat_age) + s(birth_Y_M_num) + s(month, bs="cc") + s(mean_Alt_mean2)+ parity_cat + sex + Urban3 + Language + mother_nationality_cat2  + civil_status3 + HW + GR + COVID_first_wave + COVID_second_wave, family="binomial", data=bevn_eco_in7_M_SSEP1)  
m_PTB_bam_H_SSEP1 <- bam(PTB ~ s(BW) + s(mat_age) + s(birth_Y_M_num) + s(month, bs="cc") + s(mean_Alt_mean2)+ parity_cat + sex + Urban3 + Language + mother_nationality_cat2  + civil_status3 + HW + GR + COVID_first_wave + COVID_second_wave, family="binomial", data=bevn_eco_in7_H_SSEP1)  

#function to extract the plot information
plot_m_PTB_bam_L_SSEP1 <- GAM_plot_function_binary(m_PTB_bam_L_SSEP1, 3) %>%
  mutate(SEP="low")
plot_m_PTB_bam_M_SSEP1 <- GAM_plot_function_binary(m_PTB_bam_M_SSEP1, 3) %>%
  mutate(SEP="medium")
plot_m_PTB_bam_H_SSEP1 <- GAM_plot_function_binary(m_PTB_bam_H_SSEP1, 3) %>%
  mutate(SEP="high")
```


```{r}
x_date <-   bevn_eco_in7 %>% #careful, mayhave to change the dataset if I later work with smaller time ranges!
  select(birth_Y_M, birth_Y_M_num) %>%
  distinct(birth_Y_M, .keep_all = TRUE) %>%
  rename(x=birth_Y_M_num)

plot_PTB_SEP <- plot_m_PTB_bam_L_SSEP1  %>%
  rbind(plot_m_PTB_bam_M_SSEP1 ) %>%
  rbind(plot_m_PTB_bam_H_SSEP1 ) %>%
  mutate(x=round(x,0)) %>%
  left_join(x_date) %>%
  mutate(date_x= ymd(paste0(birth_Y_M,"-01")))

# graph parameters: later, to set in the master file
lwdline <- 1.5 
size_axis <- 12
size_axis_title <- 15
size_legend <- 10
size_legend_title <- 13
lim1 <- as.POSIXct(ymd("2007-01-01"))
lim2 <- as.POSIXct(ymd("2021-12-01"))

ggplot_PTB_SEP <- ggplot(data=plot_PTB_SEP)+
  geom_line(aes(x=as.POSIXct(date_x),y=fit,col=SEP),lwd=lwdline)+
  geom_ribbon(aes(x=as.POSIXct(date_x),ymin=CIl,ymax=CIu,fill=SEP),alpha=0.15,lwd=lwdline)+
  xlab("Timeline (years)")+
  ylab("Preterm birth")+
  # ylim(c(-10,5))+
  # scale_colour_manual("",
  #                     values = c("#555555","#555555","#555555"),
  #                     limits=c("fitall","CIlall","CIuall"),
  #                     labels=c("fully adjusted","95% CI","95% CI"))+
  scale_colour_manual('SSEP',                                                #colour manual is for the line
                      limits=c("low","medium", "high"),
                      # labels=c("fully adjusted","95% CI","95% CI"),
                      values =c("#69D8F3","#9557DC", "#57DC7F"))+
  scale_fill_manual('SSEP',                                              # fill is for CI
                    limits=c("low","medium", "high"), 
                    # labels=c("fully adjusted","95% CI","95% CI"),  
                    values =c("#69D8F3","#9557DC", "#57DC7F"))+
  scale_x_datetime( breaks = date_breaks("12 month"), 
                    labels = label_date_short(),
                    limits =c(min(lim1), max(lim2)),
                    expand = c(0,0)) +
  theme_bw()+
  theme(axis.text.y=element_text(color="black",size=size_axis),
        axis.text.x=element_text(color="black",size=size_axis,angle=45,hjust=1),
        axis.title=element_text(size=size_axis_title),
        legend.text=element_text(size=size_legend),
        legend.title=element_text(size=size_legend_title),
        legend.position="bottom")

ggplot_PTB_SEP
```

# Stratification by maternal nationality
```{r include=FALSE}
m_PTB_bam_swiss <- bam(PTB ~ s(BW) + s(mat_age) + s(birth_Y_M_num) + s(month, bs="cc") + s(mean_ssep2) + s(mean_Alt_mean2)+ parity_cat + sex + Urban3 + Language + civil_status3 + HW + GR + COVID_first_wave + COVID_second_wave, family="binomial", data=bevn_eco_in7_Swiss)  
m_PTB_bam_Afr <- bam(PTB ~ s(BW) + s(mat_age) + s(birth_Y_M_num) + s(month, bs="cc") + s(mean_ssep2) + s(mean_Alt_mean2)+ parity_cat + sex + Urban3 + Language + civil_status3 + HW + GR + COVID_first_wave + COVID_second_wave, family="binomial", data=bevn_eco_in7_Afr)  
m_PTB_bam_Asi <- bam(PTB ~ s(BW) + s(mat_age) + s(birth_Y_M_num) + s(month, bs="cc") + s(mean_ssep2) + s(mean_Alt_mean2)+ parity_cat + sex + Urban3 + Language + civil_status3 + HW + GR + COVID_first_wave + COVID_second_wave, family="binomial", data=bevn_eco_in7_Asi)  
m_PTB_bam_Eur <- bam(PTB ~ s(BW) + s(mat_age) + s(birth_Y_M_num) + s(month, bs="cc") + s(mean_ssep2) + s(mean_Alt_mean2)+ parity_cat + sex + Urban3 + Language + civil_status3 + HW + GR + COVID_first_wave + COVID_second_wave, family="binomial", data=bevn_eco_in7_Eur)  
m_PTB_bam_Nort_Am <- bam(PTB ~ s(BW) + s(mat_age) + s(birth_Y_M_num) + s(month, bs="cc") + s(mean_ssep2) + s(mean_Alt_mean2)+ parity_cat + sex + Urban3 + Language + civil_status3 + HW + GR + COVID_first_wave + COVID_second_wave, family="binomial", data=bevn_eco_in7_Nort_Am)  
m_PTB_bam_S_C_Am <- bam(PTB ~ s(BW) + s(mat_age) + s(birth_Y_M_num) + s(month, bs="cc") + s(mean_ssep2) + s(mean_Alt_mean2)+ parity_cat + sex + Urban3 + Language + civil_status3 + HW + GR + COVID_first_wave + COVID_second_wave, family="binomial", data=bevn_eco_in7_S_C_Am)  


#function to extract the plot information
plot_m_PTB_bam_swiss <- GAM_plot_function_binary(m_PTB_bam_swiss, 3) %>%
  mutate(nationality="Swiss")
plot_m_PTB_bam_Afr <- GAM_plot_function_binary(m_PTB_bam_Afr, 3) %>%
  mutate(nationality="African")
plot_m_PTB_bam_Asi <- GAM_plot_function_binary(m_PTB_bam_Asi, 3) %>%
  mutate(nationality="Asian")
plot_m_PTB_bam_Eur <- GAM_plot_function_binary(m_PTB_bam_Eur, 3) %>%
  mutate(nationality="European")
plot_m_PTB_bam_Nort_Am <- GAM_plot_function_binary(m_PTB_bam_Nort_Am, 3) %>%
  mutate(nationality="Northern American")
plot_m_PTB_bam_S_C_Am <- GAM_plot_function_binary(m_PTB_bam_S_C_Am, 3) %>%
  mutate(nationality="Southern/Central American")
```


```{r}
plot_PTB_nationality <- plot_m_PTB_bam_swiss %>%
  rbind(plot_m_PTB_bam_Afr) %>%
  rbind(plot_m_PTB_bam_Asi) %>%
  rbind(plot_m_PTB_bam_Eur) %>%
  rbind(plot_m_PTB_bam_Nort_Am) %>%
  rbind(plot_m_PTB_bam_S_C_Am) %>%
  mutate(x=round(x,0)) %>%
  left_join(x_date) %>%
  mutate(date_x= ymd(paste0(birth_Y_M,"-01")))

ggplot_PTB_nationality <- ggplot(data=plot_PTB_nationality)+
  geom_line(aes(x=as.POSIXct(date_x),y=fit,col=nationality),lwd=lwdline)+
  geom_ribbon(aes(x=as.POSIXct(date_x),ymin=CIl,ymax=CIu,fill=nationality),alpha=0.15,lwd=lwdline)+
  xlab("Timeline (years)")+
  ylab("Preterm birth")+
  # ylim(c(-10,5))+
  # scale_colour_manual("",
  #                     values = c("#555555","#555555","#555555"),
  #                     limits=c("fitall","CIlall","CIuall"),
  #                     labels=c("fully adjusted","95% CI","95% CI"))+
  scale_colour_manual('Maternal nationality',
                      limits=c("Swiss","African", "Asian", "European", "Northern American", "Southern/Central American"),
                      # labels=c("fully adjusted","95% CI","95% CI"),
                      values =c("#69D8F3","#9557DC", "#8B0000", "#558621", "#57DC7F", "#666975"))+
  scale_fill_manual('Maternal nationality',
                    limits=c("Swiss","African", "Asian", "European", "Northern American", "Southern/Central American"),
                    # labels=c("fully adjusted","95% CI","95% CI"),
                    values =c("#69D8F3","#9557DC", "#8B0000", "#558621", "#57DC7F", "#666975"))+
  scale_x_datetime( breaks = date_breaks("12 month"), 
                    labels = label_date_short(),
                    limits =c(min(lim1), max(lim2)),
                    expand = c(0,0)) +
  theme_bw()+
  theme(axis.text.y=element_text(color="black",size=size_axis),
        axis.text.x=element_text(color="black",size=size_axis,angle=45,hjust=1),
        axis.title=element_text(size=size_axis_title),
        legend.text=element_text(size=size_legend),
        legend.title=element_text(size=size_legend_title),
        legend.position="bottom")

ggplot_PTB_nationality
```

# Stratification by langage region

```{r include=FALSE}
m_PTB_bam_German<- bam(PTB ~ s(BW) + s(mat_age) + s(birth_Y_M_num) + s(month, bs="cc") + s(mean_ssep2) +s(mean_Alt_mean2)+ parity_cat + sex + Urban3 + mother_nationality_cat2  + civil_status3 + HW + GR + COVID_first_wave + COVID_second_wave, family="binomial", data=bevn_eco_in7_German) 
m_PTB_bam_French<- bam(PTB ~ s(BW) + s(mat_age) + s(birth_Y_M_num) + s(month, bs="cc") + s(mean_ssep2) +s(mean_Alt_mean2)+ parity_cat + sex + Urban3 + mother_nationality_cat2  + civil_status3 + HW + GR + COVID_first_wave + COVID_second_wave, family="binomial", data=bevn_eco_in7_French)  
m_PTB_bam_Italian<- bam(PTB ~ s(BW) + s(mat_age) + s(birth_Y_M_num) + s(month, bs="cc") + s(mean_ssep2) +s(mean_Alt_mean2)+ parity_cat + sex + Urban3 + mother_nationality_cat2  + civil_status3 + HW + GR + COVID_first_wave + COVID_second_wave, family="binomial", data=bevn_eco_in7_Italian)  
 
# extracting the plot information
plot_m_PTB_bam_German <- GAM_plot_function_binary(m_PTB_bam_German, 3) %>%
  mutate(language_region="German")
plot_m_PTB_bam_French <- GAM_plot_function_binary(m_PTB_bam_French, 3) %>%
  mutate(language_region="French")
plot_m_PTB_bam_Italian <- GAM_plot_function_binary(m_PTB_bam_Italian, 3) %>%
  mutate(language_region="Italian")
```


```{r}
plot_PTB_language <- plot_m_PTB_bam_German %>%
  rbind(plot_m_PTB_bam_French) %>%
  rbind(plot_m_PTB_bam_Italian) %>%
  mutate(x=round(x,0)) %>%
  left_join(x_date) %>%
  mutate(date_x= ymd(paste0(birth_Y_M,"-01")))

ggplot_PTB_Language_region <- ggplot(data=plot_PTB_language)+
  geom_line(aes(x=as.POSIXct(date_x),y=fit,col=language_region),lwd=lwdline)+
  geom_ribbon(aes(x=as.POSIXct(date_x),ymin=CIl,ymax=CIu,fill=language_region),alpha=0.15,lwd=lwdline)+
  xlab("Timeline (years)")+
  ylab("Preterm birh")+
  # ylim(c(-10,5))+
  # scale_colour_manual("",
  #                     values = c("#555555","#555555","#555555"),
  #                     limits=c("fitall","CIlall","CIuall"),
  #                     labels=c("fully adjusted","95% CI","95% CI"))+
  scale_colour_manual('Language region',
                      limits=c("German","French", "Italian"),
                      # labels=c("fully adjusted","95% CI","95% CI"),
                      values =c("#69D8F3","#9557DC", "#57DC7F"))+
  scale_fill_manual('Language region',
                    limits=c("German","French", "Italian"),
                    # labels=c("fully adjusted","95% CI","95% CI"),
                    values =c("#69D8F3","#9557DC", "#57DC7F"))+
  scale_x_datetime( breaks = date_breaks("12 month"), 
                    labels = label_date_short(),
                    limits =c(min(lim1), max(lim2)),
                    expand = c(0,0)) +
  theme_bw()+
  theme(axis.text.y=element_text(color="black",size=size_axis),
        axis.text.x=element_text(color="black",size=size_axis,angle=45,hjust=1),
        axis.title=element_text(size=size_axis_title),
        legend.text=element_text(size=size_legend),
        legend.title=element_text(size=size_legend_title),
        legend.position="bottom")

ggplot_PTB_Language_region
```

# Stratification by maternal age

```{r include=FALSE}
m_PTB_bam_below32 <- bam(PTB~ s(BW) + s(birth_Y_M_num) + s(month, bs="cc") + s(mean_ssep2) + s(mean_Alt_mean2)+ sex + Urban3 + Language + mother_nationality_cat2 + civil_status3 + HW + GR + COVID_first_wave + COVID_second_wave, family="binomial", data=bevn_eco_in7_below32) 
m_PTB_bam_above32 <- bam(PTB~ s(BW) + s(birth_Y_M_num) + s(month, bs="cc") + s(mean_ssep2) + s(mean_Alt_mean2) + sex + Urban3 + Language + mother_nationality_cat2 + civil_status3 + HW + GR + COVID_first_wave + COVID_second_wave, family="binomial", data=bevn_eco_in7_above_32)  
 
# extracting the plot information
plot_m_PTB_bam_below32<- GAM_plot_function_binary(m_PTB_bam_below32, 2) %>%
  mutate(maternal_age="< 32 years old")
plot_m_PTB_bam_above32 <- GAM_plot_function_binary(m_PTB_bam_above32, 2) %>%
  mutate(maternal_age=">= 32 years old")
```


```{r}
plot_PTB_mat_age <- plot_m_PTB_bam_below32 %>%
  rbind(plot_m_PTB_bam_above32) %>%
  mutate(x=round(x,0)) %>%
  left_join(x_date) %>%
  mutate(date_x= ymd(paste0(birth_Y_M,"-01")))

ggplot_PTB_mat_age <- ggplot(data=plot_PTB_mat_age)+
  geom_line(aes(x=as.POSIXct(date_x),y=fit,col=maternal_age),lwd=lwdline)+
  geom_ribbon(aes(x=as.POSIXct(date_x),ymin=CIl,ymax=CIu,fill=maternal_age),alpha=0.15,lwd=lwdline)+
  xlab("Timeline (years)")+
  ylab("Preterm birh risk")+
  scale_colour_manual('Maternal age',
                      limits=c("< 32 years old",">= 32 years old"),
                      # labels=c("fully adjusted","95% CI","95% CI"),
                      values =c("#69D8F3","#9557DC"))+
  scale_fill_manual('Maternal age',
                    limits=c("< 32 years old",">= 32 years old"),
                    # labels=c("fully adjusted","95% CI","95% CI"),
                    values =c("#69D8F3","#9557DC"))+
  scale_x_datetime( breaks = date_breaks("12 month"), 
                    labels = label_date_short(),
                    limits =c(min(lim1), max(lim2)),
                    expand = c(0,0)) +
  theme_bw()+
  theme(axis.text.y=element_text(color="black",size=size_axis),
        axis.text.x=element_text(color="black",size=size_axis,angle=45,hjust=1),
        axis.title=element_text(size=size_axis_title),
        legend.text=element_text(size=size_legend),
        legend.title=element_text(size=size_legend_title),
        legend.position="bottom")

ggplot_PTB_mat_age
```