---
title: "Graphics"
author: "Mathilde Le Vu"
date:  "`r Sys.Date()`"
html_document: 
output:
  rmdformats::robobook:
    code_folding: show
    self_contained: true
    highlight: pygments
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Histogram: maternal age distribution 
```{r}
bevn_eco_in7 %>% 
  ggplot(aes(x = mat_age)) + 
  geom_histogram()

```



# Histogram: maternal nationality through the years
```{r}
gg_nation_birthy <- ggplot(bevn_eco_in7,
       aes(x=birthyear, fill=mother_nationality_cat2)) + 
  geom_bar(position = "fill") 

gg_nation_birthy +  ggtitle("Maternal nationality through the years") +
 scale_x_continuous(breaks = c(2007, 2010, 2013, 2016, 2020))
```

# Histogram: maternal civil status through the years
```{r}
gg_nation_birthy <- ggplot(bevn_eco_in7,
       aes(x=birthyear, fill=civil_status2)) + 
  geom_bar(position = "fill") 

gg_nation_birthy +  ggtitle("Maternal civil status through the years") +
 scale_x_continuous(breaks = c(2007, 2010, 2013, 2016, 2020))
```

# Kernel plots
## Birthweight 

```{r}
BW_sex <- ggplot(bevn_eco_in7, aes(x=BW, colour=sex)) + geom_density()
BW_sex

BW_birthyear_in7 <- ggplot(bevn_eco_in7, aes(x=BW, colour=as.factor(birthyear))) + geom_density()
BW_birthyear_in7
BW_birthyear_in7 + xlim(1500, 5500)
BW_birthyear_in7 + xlim(3000, 3800)


BW_birthyear_in6 <- ggplot(bevn_eco_in6, aes(x=BW, colour=as.factor(birthyear))) + geom_density()
BW_birthyear_in6
BW_birthyear_in6 + xlim(1500, 5500)
BW_birthyear_in6 + xlim(3000, 3800)

BW_birthyear_in <- ggplot(bevn_eco, aes(x=BW, colour=as.factor(birthyear))) + geom_density()
BW_birthyear_in
BW_birthyear_in + xlim(1500, 5500)
BW_birthyear_in + xlim(3000, 3800)

#maternal age
matage_birthyear_in7 <- ggplot(bevn_eco_in7, aes(x=mat_age, colour=as.factor(birthyear))) + geom_density()
matage_birthyear_in7
```


## Gestational age

```{r}
GA_sex <- ggplot(bevn_eco_in7, aes(x=GA_days, colour=sex)) + geom_density()
GA_sex + xlim(240,300)

GA_birthyear_in <- ggplot(bevn_eco_in7, aes(x=GA_days, colour=as.factor(birthyear))) + geom_density()
GA_birthyear_in
GA_birthyear_in + xlim(240, 300)

GA_birthyear_in6 <- ggplot(bevn_eco_in7, aes(x=GA_days, colour=as.factor(birthyear))) + geom_density()
GA_birthyear_in6
GA_birthyear_in6 + xlim(240, 300)

GA_birthyear_in7 <- ggplot(bevn_eco_in7, aes(x=GA_days, colour=as.factor(birthyear))) + geom_density()
GA_birthyear_in7
GA_birthyear_in7 + xlim(240, 300)
```
## BW categorical, through the years 
```{r}
# p1 <- bevn_eco_in7 %>% 
#   ggplot(aes(x = birthyear, fill = BW_cat3)) + 
#   geom_bar(position = "fill") + 
#   ylab("proportion")
# p1
```

