---
title: 'Trimester effect: exposure in 1st vs 3rd trim, LBW.'
author: "Mathilde Le Vu"
date: "2024-02-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## First trimester exposure 
```{r echo=FALSE}
  m_LBW_1st_trim <- bam(LBW ~ s(mat_age) + birth_Y_M_num+  s(month, bs="cc") + mean_ssep2_by_10 + mean_Alt_mean2_by_100+ parity_cat+ sex + Urban3 + Language + mother_nationality_cat2 + civil_status3 + HW_first_trimester + GR_first_trimester_relativ  + covid_hosp_1st_trim_relativ, family="binomial", data=bevn_eco_in7) 

plot_m_LBW_1st_trim_mat_age <- GAM_plot_function_binary(m_LBW_1st_trim, 1)
plot_m_LBW_1st_trim_month <- GAM_plot_function_binary(m_LBW_1st_trim, 2)
```

### Graph maternal age X LBW

```{r}
plot_LBW_1st_trim_mat_age <- ggplot(data=plot_m_LBW_1st_trim_mat_age)+
  geom_line(aes(x=(x),y=fit),lwd=lwdline, color=("black"))+
  geom_ribbon(aes(x=(x),ymin=CIl,ymax=CIu),alpha=0.15,lwd=lwdline, fill='black')+
  xlab("Maternal age (years)")+
  ylab("Low birth weight probability")+
  theme_bw()+
  coord_cartesian(ylim=c(0.05,0.14)) +
  theme(axis.text.y=element_text(color="black",size=size_axis),
        axis.text.x=element_text(color="black",size=size_axis,angle=45,hjust=1),
        axis.title=element_text(size=size_axis_title),
        legend.text=element_text(size=size_legend),
        legend.title=element_text(size=size_legend_title),
        legend.position="bottom") +
  scale_x_continuous(breaks=seq(0,60,by=5),expand = c(0, 0)) +
  theme(axis.title.x = axis.title.x.position)
plot_LBW_1st_trim_mat_age
```

### Graph seasonality X LBW
```{r}
plot_LBW_1st_trim_seasonality <- ggplot(data=plot_m_LBW_1st_trim_month)+
  geom_line(aes(x=(x),y=fit),lwd=lwdline, color=("black"))+
  geom_ribbon(aes(x=(x),ymin=CIl,ymax=CIu),alpha=0.15,lwd=lwdline, fill='black')+
  xlab("Month")+
  ylab("Low birth weight probability")+
  theme_bw()+
  coord_cartesian(ylim=c(0.05,0.14)) +
  theme(axis.text.y=element_text(color="black",size=size_axis),
        axis.text.x=element_text(color="black",size=size_axis,angle=45,hjust=1),
        axis.title=element_text(size=size_axis_title),
        legend.text=element_text(size=size_legend),
        legend.title=element_text(size=size_legend_title),
        legend.position="bottom") +
  scale_x_continuous(breaks=seq(1,12,by=1),expand = c(0, 0)) +
  theme(axis.title.x = axis.title.x.position)
plot_LBW_1st_trim_seasonality
```

### Table summarizing the model

```{r}
  OR <- exp(coef(m_LBW_1st_trim))
  beta <- coef(m_LBW_1st_trim)
  Vb <- vcov(m_LBW_1st_trim, unconditional = TRUE)
  se <- sqrt(diag(Vb))
  lci <- exp(beta-1.96*se)
  uci <- exp(beta+1.96*se)
  d <- abs(beta)/1.81
  my.ci_LBW_1st_trim <- data.frame(cbind(OR, lci, uci, d))
  my.ci_LBW_1st_trim <- format(round(my.ci_LBW_1st_trim[18:20, c(1:4)], digits=2), nsmall=2)
  
pvalue_non_smooth_m_LBW_1st_trim = summary(m_LBW_1st_trim)
pvalue_non_smooth_m_LBW_1st_trim <- pvalue_non_smooth_m_LBW_1st_trim$p.table[18:20, "Pr(>|z|)"]
pvalue_non_smooth_m_LBW_1st_trim <- format(pvalue_non_smooth_m_LBW_1st_trim, scientific=FALSE)
pvalues_non_smooth_LBW_1st_trim_df <- data.frame(pvalue_non_smooth_m_LBW_1st_trim)%>%
  rename(pvalues_smooth_LBW_main=pvalue_non_smooth_m_LBW_1st_trim)

pvalues_non_smooth_LBW_1st_trim_df <- pvalues_non_smooth_LBW_1st_trim_df %>%
  rename(c(pvalue=(pvalues_smooth_LBW_main)))%>%
  mutate(pvalue=as.numeric(pvalue)) %>%
  mutate(pvalue1=pvalue)

pvalues_non_smooth_LBW_1st_trim_df$pvalue <-  format(round(pvalues_non_smooth_LBW_1st_trim_df$pvalue, digits=2), nsmall=2)

pvalues_non_smooth_LBW_1st_trim_df <- pvalues_non_smooth_LBW_1st_trim_df %>%
  mutate(pvalue1=case_when((pvalue1<0.00001) ~ "<0.0001",
                           (pvalue1<0.001)~ "<0.001",
                           (pvalue1<0.01)~ "<0.01")) 

pvalues_non_smooth_LBW_1st_trim_df$pvalue1 <- (ifelse(is.na(pvalues_non_smooth_LBW_1st_trim_df$pvalue1), 
                                             pvalues_non_smooth_LBW_1st_trim_df$pvalue, pvalues_non_smooth_LBW_1st_trim_df$pvalue1))
pvalues_non_smooth_LBW_1st_trim_df1 <- pvalues_non_smooth_LBW_1st_trim_df %>%
  select(-one_of('pvalue')) %>%
    rename("pvalue"="pvalue1") 

LBW_1st_trim <- my.ci_LBW_1st_trim %>%
  cbind(pvalues_non_smooth_LBW_1st_trim_df1)
```


## Last trimester exposure 
```{r echo=FALSE}
  m_LBW_last_trim <- bam(LBW ~ s(mat_age) + birth_Y_M_num+  s(month, bs="cc") + mean_ssep2_by_10 + mean_Alt_mean2_by_100+ parity_cat+ sex + Urban3 + Language + mother_nationality_cat2 + civil_status3 + HW_last_trimester + GR_last_trimester_relativ  + covid_hosp_last_trim_relativ, family="binomial", data=bevn_eco_in7) 

    # extracting the plot information
plot_m_LBW_last_trim_mat_age <- GAM_plot_function_binary(m_LBW_last_trim, 1)
plot_m_LBW_last_trim_month <- GAM_plot_function_binary(m_LBW_last_trim, 2)
```

### Graph maternal age X LBW

```{r}
plot_LBW_last_trim_mat_age <- ggplot(data=plot_m_LBW_last_trim_mat_age)+
  geom_line(aes(x=(x),y=fit),lwd=lwdline, color=("black"))+
  geom_ribbon(aes(x=(x),ymin=CIl,ymax=CIu),alpha=0.15,lwd=lwdline, fill='black')+
  xlab("Maternal age (years)")+
  ylab("Low birth weight probability")+
  theme_bw()+
  coord_cartesian(ylim=c(0.05,0.14)) +
  theme(axis.text.y=element_text(color="black",size=size_axis),
        axis.text.x=element_text(color="black",size=size_axis,angle=45,hjust=1),
        axis.title=element_text(size=size_axis_title),
        legend.text=element_text(size=size_legend),
        legend.title=element_text(size=size_legend_title),
        legend.position="bottom") +
  scale_x_continuous(breaks=seq(0,60,by=5),expand = c(0, 0)) +
  theme(axis.title.x = axis.title.x.position)
plot_LBW_1st_trim_mat_age
```

### Graph seasonality X LBW
```{r}
plot_LBW_last_trim_seasonality <- ggplot(data=plot_m_LBW_last_trim_month)+
  geom_line(aes(x=(x),y=fit),lwd=lwdline, color=("black"))+
  geom_ribbon(aes(x=(x),ymin=CIl,ymax=CIu),alpha=0.15,lwd=lwdline, fill='black')+
  xlab("Month")+
  ylab("Low birth weight probability")+
  theme_bw()+
  coord_cartesian(ylim=c(0.05,0.14)) +
  theme(axis.text.y=element_text(color="black",size=size_axis),
        axis.text.x=element_text(color="black",size=size_axis,angle=45,hjust=1),
        axis.title=element_text(size=size_axis_title),
        legend.text=element_text(size=size_legend),
        legend.title=element_text(size=size_legend_title),
        legend.position="bottom") +
  scale_x_continuous(breaks=seq(1,12,by=1),expand = c(0, 0)) +
  theme(axis.title.x = axis.title.x.position)
plot_LBW_1st_trim_seasonality
```

### Table summarizing the model

```{r}
  OR <- exp(coef(m_LBW_last_trim))
  beta <- coef(m_LBW_last_trim)
  Vb <- vcov(m_LBW_last_trim, unconditional = TRUE)
  se <- sqrt(diag(Vb))
  lci <- exp(beta-1.96*se)
  uci <- exp(beta+1.96*se)
  d <- abs(beta)/1.81
  my.ci_LBW_last_trim <- data.frame(cbind(OR, lci, uci, d))
  my.ci_LBW_last_trim <- format(round(my.ci_LBW_last_trim[18:20, c(1:4)], digits=2), nsmall=2)
  
pvalue_non_smooth_m_LBW_last_trim = summary(m_LBW_last_trim)
pvalue_non_smooth_m_LBW_last_trim <- pvalue_non_smooth_m_LBW_last_trim$p.table[18:20, "Pr(>|z|)"]
pvalue_non_smooth_m_LBW_last_trim <- format(pvalue_non_smooth_m_LBW_last_trim, scientific=FALSE)
pvalue_non_smooth_m_LBW_last_trim_df <- data.frame(pvalue_non_smooth_m_LBW_last_trim)%>%
  rename(pvalues_smooth_LBW_main=pvalue_non_smooth_m_LBW_last_trim)

pvalue_non_smooth_m_LBW_last_trim_df <- pvalue_non_smooth_m_LBW_last_trim_df %>%
  rename(c(pvalue=(pvalues_smooth_LBW_main)))%>%
  mutate(pvalue=as.numeric(pvalue)) %>%
  mutate(pvalue1=pvalue)

pvalue_non_smooth_m_LBW_last_trim_df$pvalue <-  format(round(pvalue_non_smooth_m_LBW_last_trim_df$pvalue, digits=2), nsmall=2)

pvalue_non_smooth_m_LBW_last_trim_df <- pvalue_non_smooth_m_LBW_last_trim_df %>%
  mutate(pvalue1=case_when((pvalue1<0.00001) ~ "<0.0001",
                           (pvalue1<0.001)~ "<0.001",
                           (pvalue1<0.01)~ "<0.01")) 

pvalue_non_smooth_m_LBW_last_trim_df$pvalue1 <- (ifelse(is.na(pvalue_non_smooth_m_LBW_last_trim_df$pvalue1), 
                                             pvalue_non_smooth_m_LBW_last_trim_df$pvalue, pvalue_non_smooth_m_LBW_last_trim_df$pvalue1))
pvalue_non_smooth_m_LBW_last_trim_df1 <- pvalue_non_smooth_m_LBW_last_trim_df %>%
  select(-one_of('pvalue')) %>%
    rename("pvalue"="pvalue1") 

LBW_last_trim <- my.ci_LBW_last_trim %>%
  cbind(pvalue_non_smooth_m_LBW_last_trim_df1)
```
