---
title: "PTB GAM stratified by maternal nationality"
author: "Mathilde Le Vu"
date:  "`r Sys.Date()`"
html_document: 
output:
  rmdformats::robobook:
    code_folding: show
    self_contained: true
    highlight: pygments
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Swiss

```{r}
m_PTB_bam_swiss <- bam(PTB ~ s(BW) + s(mat_age) + s(birth_Y_M_num) + s(month, bs="cc") + s(mean_ssep2) + s(mean_Alt_mean2)+ parity_cat + sex + Urban3 + Language + civil_status3 + HW + GR + COVID_first_wave + COVID_second_wave, family="binomial", data=bevn_eco_in7_Swiss)  
summary(m_PTB_bam_swiss)
  plot(m_PTB_bam_swiss, trans = plogis, select=1, shift = coef(m_PTB_bam_swiss)[1], shade = TRUE, shade.col = "lightblue") #BW
  plot(m_PTB_bam_swiss, trans = plogis, select=2, ylim=c(0, 0.04), shift = coef(m_PTB_bam_swiss)[1], shade = TRUE, shade.col = "lightblue") #mat age
  plot(m_PTB_bam_swiss, trans = plogis, select=3, ylim=c(0.005, 0.03), shift = coef(m_PTB_bam_swiss)[1], shade = TRUE, shade.col = "lightblue") #time
  plot(m_PTB_bam_swiss, trans = plogis, select=4, ylim=c(0.015, 0.025), shift = coef(m_PTB_bam_swiss)[1], shade = TRUE, shade.col = "lightblue") #month
    plot(m_PTB_bam_swiss, trans = plogis, select=5, ylim=c(0.010, 0.025), shift = coef(m_PTB_bam_swiss)[1], shade = TRUE, shade.col = "lightblue") #mean_ssep2
  plot(m_PTB_bam_swiss, trans = plogis, select=6, ylim=c(0.0005, 0.025), shift = coef(m_PTB_bam_swiss)[1], shade = TRUE, shade.col = "lightblue") #altitude
  
  k.check(m_PTB_bam_swiss) 
  concurvity(m_PTB_bam_swiss)
```

```{r}
  tab_m_PTB_bam_Swiss <- round(head(estimates_binary(m_PTB_bam_swiss), 13), 2)
  tab_m_PTB_bam_Swiss
```

# African

```{r}
m_PTB_bam_Afr <- bam(PTB ~ s(BW) + s(mat_age) + s(birth_Y_M_num) + s(month, bs="cc") + s(mean_ssep2) + s(mean_Alt_mean2)+ parity_cat + sex + Urban3 + Language + civil_status3 + HW + GR + COVID_first_wave + COVID_second_wave, family="binomial", data=bevn_eco_in7_Afr)  
summary(m_PTB_bam_Afr)
  plot(m_PTB_bam_Afr, trans = plogis, select=1, shift = coef(m_PTB_bam_Afr)[1], shade = TRUE, shade.col = "lightblue") #BW
  plot(m_PTB_bam_Afr, trans = plogis, select=2, ylim=c(0, 0.065), shift = coef(m_PTB_bam_Afr)[1], shade = TRUE, shade.col = "lightblue") #mat age
  plot(m_PTB_bam_Afr, trans = plogis, select=3, ylim=c(0.005, 0.03), shift = coef(m_PTB_bam_Afr)[1], shade = TRUE, shade.col = "lightblue") #time
  plot(m_PTB_bam_Afr, trans = plogis, select=4, ylim=c(0.010, 0.025), shift = coef(m_PTB_bam_Afr)[1], shade = TRUE, shade.col = "lightblue") #month
    plot(m_PTB_bam_Afr, trans = plogis, select=5, ylim=c(0.010, 0.025), shift = coef(m_PTB_bam_Afr)[1], shade = TRUE, shade.col = "lightblue") #mean_ssep2
  plot(m_PTB_bam_Afr, trans = plogis, select=6, ylim=c(0.0005, 0.025), shift = coef(m_PTB_bam_Afr)[1], shade = TRUE, shade.col = "lightblue") #altitude
  
  k.check(m_PTB_bam_Afr) 
  concurvity(m_PTB_bam_Afr)
```

```{r}
  tab_m_PTB_bam_Afr <- round(head(estimates_binary(m_PTB_bam_Afr), 13), 2)
  tab_m_PTB_bam_Afr
```

# Asian

```{r}
m_PTB_bam_Asi <- bam(PTB ~ s(BW) + s(mat_age) + s(birth_Y_M_num) + s(month, bs="cc") + s(mean_ssep2) + s(mean_Alt_mean2)+ parity_cat + sex + Urban3 + Language + civil_status3 + HW + GR + COVID_first_wave + COVID_second_wave, family="binomial", data=bevn_eco_in7_Asi)  
summary(m_PTB_bam_Asi)
    plot(m_PTB_bam_Asi, trans = plogis, select=1, shift = coef(m_PTB_bam_Asi)[1], shade = TRUE, shade.col = "lightblue") #BW
  plot(m_PTB_bam_Asi, trans = plogis, select=2, ylim=c(0, 0.065), shift = coef(m_PTB_bam_Asi)[1], shade = TRUE, shade.col = "lightblue") #mat age
  plot(m_PTB_bam_Asi, trans = plogis, select=3, ylim=c(0.005, 0.03), shift = coef(m_PTB_bam_Asi)[1], shade = TRUE, shade.col = "lightblue") #time
  plot(m_PTB_bam_Asi, trans = plogis, select=4, ylim=c(0.015, 0.025), shift = coef(m_PTB_bam_Asi)[1], shade = TRUE, shade.col = "lightblue") #month
  plot(m_PTB_bam_Asi, trans = plogis, select=5, ylim=c(0.015, 0.04), shift = coef(m_PTB_bam_Asi)[1], shade = TRUE, shade.col = "lightblue") #mean_ssep2
  plot(m_PTB_bam_Asi, trans = plogis, select=6, ylim=c(0.0005, 0.035), shift = coef(m_PTB_bam_Asi)[1], shade = TRUE, shade.col = "lightblue") #altitude
  k.check(m_PTB_bam_Asi) 
  concurvity(m_PTB_bam_Asi)
```

```{r}
  tab_m_PTB_bam_Asi <- round(head(estimates_binary(m_PTB_bam_Asi), 13), 2)
  tab_m_PTB_bam_Asi
```

# European (non-Swiss)

```{r}
m_PTB_bam_Eur <- bam(PTB ~ s(BW) + s(mat_age) + s(birth_Y_M_num) + s(month, bs="cc") + s(mean_ssep2) + s(mean_Alt_mean2)+ parity_cat + sex + Urban3 + Language + civil_status3 + HW + GR + COVID_first_wave + COVID_second_wave, family="binomial", data=bevn_eco_in7_Eur)  
summary(m_PTB_bam_Eur)
    plot(m_PTB_bam_Eur, trans = plogis, select=1, shift = coef(m_PTB_bam_Eur)[1], shade = TRUE, shade.col = "lightblue") #BW
  plot(m_PTB_bam_Eur, trans = plogis, select=2, ylim=c(0, 0.065), shift = coef(m_PTB_bam_Eur)[1], shade = TRUE, shade.col = "lightblue") #mat age
  plot(m_PTB_bam_Eur, trans = plogis, select=3, ylim=c(0.005, 0.03), shift = coef(m_PTB_bam_Eur)[1], shade = TRUE, shade.col = "lightblue") #time
  plot(m_PTB_bam_Eur, trans = plogis, select=4, ylim=c(0.015, 0.025), shift = coef(m_PTB_bam_Eur)[1], shade = TRUE, shade.col = "lightblue") #month
  plot(m_PTB_bam_Eur, trans = plogis, select=5, ylim=c(0.005, 0.03), shift = coef(m_PTB_bam_Eur)[1], shade = TRUE, shade.col = "lightblue") #mean_ssep2
  plot(m_PTB_bam_Eur, trans = plogis, select=6, ylim=c(0.0005, 0.025), shift = coef(m_PTB_bam_Eur)[1], shade = TRUE, shade.col = "lightblue") #altitude
  
  k.check(m_PTB_bam_Eur) 
  concurvity(m_PTB_bam_Eur)
```

```{r}
  tab_m_PTB_bam_Eur <- round(head(estimates_binary(m_PTB_bam_Eur), 13), 2)
  tab_m_PTB_bam_Eur
```

# Nothern American

```{r}
m_PTB_bam_Nort_Am <- bam(PTB ~ s(BW) + s(mat_age) + s(birth_Y_M_num) + s(month, bs="cc") + s(mean_ssep2) + s(mean_Alt_mean2)+ parity_cat + sex + Urban3 + Language + civil_status3 + HW + GR + COVID_first_wave + COVID_second_wave, family="binomial", data=bevn_eco_in7_Nort_Am)  
summary(m_PTB_bam_Nort_Am)
  plot(m_PTB_bam_Nort_Am, trans = plogis, select=1, shift = coef(m_PTB_bam_Nort_Am)[1], shade = TRUE, shade.col = "lightblue") #BW
  plot(m_PTB_bam_Nort_Am, trans = plogis, select=2, ylim=c(0, 0.065), shift = coef(m_PTB_bam_Nort_Am)[1], shade = TRUE, shade.col = "lightblue") #mat age
  plot(m_PTB_bam_Nort_Am, trans = plogis, select=3, ylim=c(0.005, 0.03), shift = coef(m_PTB_bam_Nort_Am)[1], shade = TRUE, shade.col = "lightblue") #time
  plot(m_PTB_bam_Nort_Am, trans = plogis, select=4, ylim=c(0.005, 0.015), shift = coef(m_PTB_bam_Nort_Am)[1], shade = TRUE, shade.col = "lightblue") #month
  plot(m_PTB_bam_Nort_Am, trans = plogis, select=5, ylim=c(0.002, 0.015), shift = coef(m_PTB_bam_Nort_Am)[1], shade = TRUE, shade.col = "lightblue") #mean_ssep2
  plot(m_PTB_bam_Nort_Am, trans = plogis, select=6, ylim=c(0.0005, 0.025), shift = coef(m_PTB_bam_Nort_Am)[1], shade = TRUE, shade.col = "lightblue") #altitude
  
  k.check(m_PTB_bam_Nort_Am) 
  concurvity(m_PTB_bam_Nort_Am)
```

```{r}
  tab_m_PTB_Nort_Am <- round(head(estimates_binary(m_PTB_bam_Nort_Am), 13), 2)
  tab_m_PTB_Nort_Am
```


# Southern and Central American
```{r}
m_PTB_bam_S_C_Am <- bam(PTB ~ s(BW) + s(mat_age) + s(birth_Y_M_num) + s(month, bs="cc") + s(mean_ssep2) + s(mean_Alt_mean2)+ parity_cat + sex + Urban3 + Language + civil_status3 + HW + GR + COVID_first_wave + COVID_second_wave, family="binomial", data=bevn_eco_in7_S_C_Am)  
summary(m_PTB_bam_S_C_Am)
    plot(m_PTB_bam_S_C_Am, trans = plogis, select=1, shift = coef(m_PTB_bam_S_C_Am)[1], shade = TRUE, shade.col = "lightblue") #BW
  plot(m_PTB_bam_S_C_Am, trans = plogis, select=2, ylim=c(0, 0.065), shift = coef(m_PTB_bam_S_C_Am)[1], shade = TRUE, shade.col = "lightblue") #mat age
  plot(m_PTB_bam_S_C_Am, trans = plogis, select=3, ylim=c(0.005, 0.03), shift = coef(m_PTB_bam_S_C_Am)[1], shade = TRUE, shade.col = "lightblue") #time
  plot(m_PTB_bam_S_C_Am, trans = plogis, select=4, ylim=c(0.015, 0.025), shift = coef(m_PTB_bam_S_C_Am)[1], shade = TRUE, shade.col = "lightblue") #month
  plot(m_PTB_bam_S_C_Am, trans = plogis, select=5, ylim=c(0.010, 0.025), shift = coef(m_PTB_bam_S_C_Am)[1], shade = TRUE, shade.col = "lightblue") #mean_ssep2
  plot(m_PTB_bam_S_C_Am, trans = plogis, select=6, ylim=c(0.0005, 0.035), shift = coef(m_PTB_bam_S_C_Am)[1], shade = TRUE, shade.col = "lightblue") #altitude
  
  k.check(m_PTB_bam_S_C_Am) 
  concurvity(m_PTB_bam_S_C_Am)
```

```{r}
  tab_m_PTB_S_C_Am <- round(head(estimates_binary(m_PTB_bam_S_C_Am), 13), 2)
  tab_m_PTB_S_C_Am
```
