---
title: "PTB GAM stratified by Language Region"
author: "Mathilde Le Vu"
date:  "`r Sys.Date()`"
html_document: 
output:
  rmdformats::robobook:
    code_folding: show
    self_contained: true
    highlight: pygments
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# German

```{r}
m_PTB_bam_German<- bam(PTB ~ s(BW) + s(mat_age) + s(birth_Y_M_num) + s(month, bs="cc") + s(mean_ssep2) +s(mean_Alt_mean2)+ parity_cat + sex + Urban3 + mother_nationality_cat2  + civil_status3 + HW + GR + COVID_first_wave + COVID_second_wave, family="binomial", data=bevn_eco_in7_German) 
summary(m_PTB_bam_German)
  plot(m_PTB_bam_German, trans = plogis, select=1, shift = coef(m_PTB_bam_German)[1], shade = TRUE, shade.col = "lightblue") #BW
  plot(m_PTB_bam_German, trans = plogis, select=2, ylim=c(0, 0.04), shift = coef(m_PTB_bam_German)[1], shade = TRUE, shade.col = "lightblue") #mat age
  plot(m_PTB_bam_German, trans = plogis, select=3, ylim=c(0.01, 0.03), shift = coef(m_PTB_bam_German)[1], shade = TRUE, shade.col = "lightblue") #time
  plot(m_PTB_bam_German, trans = plogis, select=4, ylim=c(0.015, 0.025), shift = coef(m_PTB_bam_German)[1], shade = TRUE, shade.col = "lightblue") #month
    plot(m_PTB_bam_German, trans = plogis, select=5, ylim=c(0.0005, 0.025), shift = coef(m_PTB_bam_German)[1], shade = TRUE, shade.col = "lightblue") #ssep
  plot(m_PTB_bam_German, trans = plogis, select=6, ylim=c(0.0005, 0.025), shift = coef(m_PTB_bam_German)[1], shade = TRUE, shade.col = "lightblue") #altitude
  
  k.check(m_PTB_bam_German) 
  concurvity(m_PTB_bam_German)
```

```{r}
  tab_m_PTB_bam_German <- round(head(estimates_binary(m_PTB_bam_German), 16), 2)
  tab_m_PTB_bam_German
```

# French

```{r}
m_PTB_bam_French<- bam(PTB ~ s(BW) + s(mat_age) + s(birth_Y_M_num) + s(month, bs="cc") + s(mean_ssep2) +s(mean_Alt_mean2)+ parity_cat + sex + Urban3 + mother_nationality_cat2  + civil_status3 + HW + GR + COVID_first_wave + COVID_second_wave, family="binomial", data=bevn_eco_in7_French)  
summary(m_PTB_bam_French)
  plot(m_PTB_bam_French, trans = plogis, select=1, shift = coef(m_PTB_bam_French)[1], shade = TRUE, shade.col = "lightblue") #BW
  plot(m_PTB_bam_French, trans = plogis, select=2, ylim=c(0, 0.065), shift = coef(m_PTB_bam_French)[1], shade = TRUE, shade.col = "lightblue") #mat age
  plot(m_PTB_bam_French, trans = plogis, select=3, ylim=c(0.01, 0.03), shift = coef(m_PTB_bam_French)[1], shade = TRUE, shade.col = "lightblue") #time
  plot(m_PTB_bam_French, trans = plogis, select=4, ylim=c(0.015, 0.025), shift = coef(m_PTB_bam_French)[1], shade = TRUE, shade.col = "lightblue") #month
    plot(m_PTB_bam_German, trans = plogis, select=5, ylim=c(0.0005, 0.025), shift = coef(m_PTB_bam_German)[1], shade = TRUE, shade.col = "lightblue") #ssep
  plot(m_PTB_bam_German, trans = plogis, select=6, ylim=c(0.0005, 0.025), shift = coef(m_PTB_bam_German)[1], shade = TRUE, shade.col = "lightblue") #altitude
  
  k.check(m_PTB_bam_French) 
  concurvity(m_PTB_bam_French)
```

```{r}
  tab_m_PTB_bam_French <- round(head(estimates_binary(m_PTB_bam_French), 16), 2)
  tab_m_PTB_bam_French
```

# Italian

```{r}
m_PTB_bam_Italian<- bam(PTB ~ s(BW) + s(mat_age) + s(birth_Y_M_num) + s(month, bs="cc") + s(mean_ssep2) +s(mean_Alt_mean2)+ parity_cat + sex + Urban3 + mother_nationality_cat2  + civil_status3 + HW + GR + COVID_first_wave + COVID_second_wave, family="binomial", data=bevn_eco_in7_Italian)  
summary(m_PTB_bam_Italian)
    plot(m_PTB_bam_Italian, trans = plogis, select=1, shift = coef(m_PTB_bam_Italian)[1], shade = TRUE, shade.col = "lightblue") #BW
  plot(m_PTB_bam_Italian, trans = plogis, select=2, ylim=c(0, 0.065), shift = coef(m_PTB_bam_Italian)[1], shade = TRUE, shade.col = "lightblue") #mat age
  plot(m_PTB_bam_Italian, trans = plogis, select=3, ylim=c(0.01, 0.03), shift = coef(m_PTB_bam_Italian)[1], shade = TRUE, shade.col = "lightblue") #time
  plot(m_PTB_bam_Italian, trans = plogis, select=4, ylim=c(0.015, 0.025), shift = coef(m_PTB_bam_Italian)[1], shade = TRUE, shade.col = "lightblue") #month
    plot(m_PTB_bam_German, trans = plogis, select=5, ylim=c(0.0005, 0.025), shift = coef(m_PTB_bam_German)[1], shade = TRUE, shade.col = "lightblue") #ssep
  plot(m_PTB_bam_German, trans = plogis, select=6, ylim=c(0.0005, 0.025), shift = coef(m_PTB_bam_German)[1], shade = TRUE, shade.col = "lightblue") #altitude
  
  k.check(m_PTB_bam_Italian) 
  concurvity(m_PTB_bam_Italian)
```

```{r}
  tab_m_PTB_bam_Italian <- round(head(estimates_binary(m_PTB_bam_Italian), 16), 2)
  tab_m_PTB_bam_Italian
```
