---
title: "PTB GAM stratified by SEP (3 groups, by tertiles)"
author: "Mathilde Le Vu"
date:  "`r Sys.Date()`"
html_document: 
output:
  rmdformats::robobook:
    code_folding: show
    self_contained: true
    highlight: pygments
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Low SEP

```{r}
m_PTB_bam_L_SSEP1 <- bam(PTB ~ s(BW) + s(mat_age) + s(birth_Y_M_num) + s(month, bs="cc") + s(mean_Alt_mean2)+ parity_cat + sex + Urban3 + Language + mother_nationality_cat2  + civil_status3 + HW + GR + COVID_first_wave + COVID_second_wave, family="binomial", data=bevn_eco_in7_L_SSEP1)  
summary(m_PTB_bam_L_SSEP1)
  plot(m_PTB_bam_L_SSEP1, trans = plogis, select=1, shift = coef(m_PTB_bam_L_SSEP1)[1], shade = TRUE, shade.col = "lightblue") #BW
  plot(m_PTB_bam_L_SSEP1, trans = plogis, select=2, ylim=c(0, 0.04), shift = coef(m_PTB_bam_L_SSEP1)[1], shade = TRUE, shade.col = "lightblue") #mat age
  plot(m_PTB_bam_L_SSEP1, trans = plogis, select=3, ylim=c(0.01, 0.03), shift = coef(m_PTB_bam_L_SSEP1)[1], shade = TRUE, shade.col = "lightblue") #time
  plot(m_PTB_bam_L_SSEP1, trans = plogis, select=4, ylim=c(0.015, 0.025), shift = coef(m_PTB_bam_L_SSEP1)[1], shade = TRUE, shade.col = "lightblue") #month
  plot(m_PTB_bam_L_SSEP1, trans = plogis, select=5, ylim=c(0.0005, 0.025), shift = coef(m_PTB_bam_L_SSEP1)[1], shade = TRUE, shade.col = "lightblue") #altitude
  
  k.check(m_PTB_bam_L_SSEP1) 
  concurvity(m_PTB_bam_L_SSEP1)
```

```{r}
#table to show OR, confidence interval and Cohen's d
  tab_m_PTB_bam_L_SSEP1 <- round(head(estimates_binary(m_PTB_bam_L_SSEP1), 18), 2)
  tab_m_PTB_bam_L_SSEP1
```

# Middle SEP

```{r}
m_PTB_bam_M_SSEP1 <- bam(PTB ~ s(BW) + s(mat_age) + s(birth_Y_M_num) + s(month, bs="cc") + s(mean_Alt_mean2)+ parity_cat + sex + Urban3 + Language + mother_nationality_cat2  + civil_status3 + HW + GR + COVID_first_wave + COVID_second_wave, family="binomial", data=bevn_eco_in7_M_SSEP1)  
summary(m_PTB_bam_M_SSEP1)
  plot(m_PTB_bam_M_SSEP1, trans = plogis, select=1, shift = coef(m_PTB_bam_M_SSEP1)[1], shade = TRUE, shade.col = "lightblue") #BW
  plot(m_PTB_bam_M_SSEP1, trans = plogis, select=2, ylim=c(0, 0.065), shift = coef(m_PTB_bam_M_SSEP1)[1], shade = TRUE, shade.col = "lightblue") #mat age
  plot(m_PTB_bam_M_SSEP1, trans = plogis, select=3, ylim=c(0.01, 0.03), shift = coef(m_PTB_bam_M_SSEP1)[1], shade = TRUE, shade.col = "lightblue") #time
  plot(m_PTB_bam_M_SSEP1, trans = plogis, select=4, ylim=c(0.015, 0.025), shift = coef(m_PTB_bam_M_SSEP1)[1], shade = TRUE, shade.col = "lightblue") #month
  plot(m_PTB_bam_M_SSEP1, trans = plogis, select=5, ylim=c(0.0005, 0.025), shift = coef(m_PTB_bam_M_SSEP1)[1], shade = TRUE, shade.col = "lightblue") #altitude
  
  k.check(m_PTB_bam_M_SSEP1) 
  concurvity(m_PTB_bam_M_SSEP1)
```

```{r}
#table to show OR, confidence interval and Cohen's d
  tab_m_PTB_bam_M_SSEP1 <- round(head(estimates_binary(m_PTB_bam_M_SSEP1), 18), 2)
  tab_m_PTB_bam_M_SSEP1
```

# High SEP

```{r}
m_PTB_bam_H_SSEP1 <- bam(PTB ~ s(BW) + s(mat_age) + s(birth_Y_M_num) + s(month, bs="cc") + s(mean_Alt_mean2)+ parity_cat + sex + Urban3 + Language + mother_nationality_cat2  + civil_status3 + HW + GR + COVID_first_wave + COVID_second_wave, family="binomial", data=bevn_eco_in7_H_SSEP1)  
summary(m_PTB_bam_H_SSEP1)
    plot(m_PTB_bam_H_SSEP1, trans = plogis, select=1, shift = coef(m_PTB_bam_H_SSEP1)[1], shade = TRUE, shade.col = "lightblue") #BW
  plot(m_PTB_bam_H_SSEP1, trans = plogis, select=2, ylim=c(0, 0.065), shift = coef(m_PTB_bam_H_SSEP1)[1], shade = TRUE, shade.col = "lightblue") #mat age
  plot(m_PTB_bam_H_SSEP1, trans = plogis, select=3, ylim=c(0.01, 0.03), shift = coef(m_PTB_bam_H_SSEP1)[1], shade = TRUE, shade.col = "lightblue") #time
  plot(m_PTB_bam_H_SSEP1, trans = plogis, select=4, ylim=c(0.015, 0.025), shift = coef(m_PTB_bam_H_SSEP1)[1], shade = TRUE, shade.col = "lightblue") #month
  plot(m_PTB_bam_H_SSEP1, trans = plogis, select=5, ylim=c(0.0005, 0.025), shift = coef(m_PTB_bam_H_SSEP1)[1], shade = TRUE, shade.col = "lightblue") #altitude
  
  k.check(m_PTB_bam_H_SSEP1) 
  concurvity(m_PTB_bam_H_SSEP1)
```

```{r}
#table to show OR, confidence interval and Cohen's d
  tab_m_PTB_bam_H_SSEP1 <- round(head(estimates_binary(m_PTB_bam_H_SSEP1), 18), 2)
  tab_m_PTB_bam_H_SSEP1
```
