---
title: 'Stratification: maternal age, first parities only'
author: "Mathilde Le Vu"
date: "2023-02-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Below 32 yo
```{r}
m_PTB_bam_below32 <- bam(PTB~ s(BW) + s(birth_Y_M_num) + s(month, bs="cc") + s(mean_ssep2) + s(mean_Alt_mean2) + sex + Urban3 + Language + mother_nationality_cat2 + civil_status3 + HW + GR + COVID_first_wave + COVID_second_wave, family="binomial", data=bevn_eco_in7_below32) 
summary(m_PTB_bam_below32)
plot(m_PTB_bam_below32, trans = plogis, select=1, shift = coef(m_PTB_bam_below32)[1], shade = TRUE, shade.col = "lightblue") #BW
plot(m_PTB_bam_below32, trans = plogis, select=2, ylim=c(0.01, 0.03), shift = coef(m_PTB_bam_below32)[1], shade = TRUE, shade.col = "lightblue") #time
  plot(m_PTB_bam_below32, trans = plogis, select=3, ylim=c(0.015, 0.025), shift = coef(m_PTB_bam_below32)[1], shade = TRUE, shade.col = "lightblue") #month
    plot(m_PTB_bam_below32, trans = plogis, select=4, ylim=c(0.0005, 0.025), shift = coef(m_PTB_bam_below32)[1], shade = TRUE, shade.col = "lightblue") #ssep
  plot(m_PTB_bam_below32, trans = plogis, select=5, ylim=c(0.0005, 0.025), shift = coef(m_PTB_bam_below32)[1], shade = TRUE, shade.col = "lightblue") #altitude
  
  plot_m_PTB_below_32 <- GAM_plot_function_binary(m_PTB_bam_below32, 2) # time
```
## Graph time variable X preterm birth

```{r}
x_date <-   bevn_eco_in7_below32 %>% #careful, mayhave to change the dataset if I later work with smaller time ranges!
  select(birth_Y_M, birth_Y_M_num) %>%
  distinct(birth_Y_M, .keep_all = TRUE) %>%
  rename(x=birth_Y_M_num)

plot_data_PTB_below32 <- plot_m_PTB_below_32 %>%
  mutate(x=round(x,0)) %>%
  left_join(x_date) %>%
  mutate(date_x= ymd(paste0(birth_Y_M,"-01")))
lim1 <- as.POSIXct(ymd("2007-01-01"))
lim2 <- as.POSIXct(ymd("2021-12-01"))

plot_PTB_below32 <- ggplot(data=plot_data_PTB_below32)+
  geom_line(aes(x=as.POSIXct(date_x),y=fit),lwd=lwdline, color=("#9557DC"))+
  geom_ribbon(aes(x=as.POSIXct(date_x),ymin=CIl,ymax=CIu),alpha=0.15,lwd=lwdline, fill='#69D8F3')+
  xlab("Timeline (years)")+
  ylab("Preterm birth probability")+
  scale_colour_manual('PTB', values =c("#9557DC"))+
  scale_fill_manual('PTB', values =c("#9557DC"))+
   scale_x_datetime( breaks = date_breaks("12 month"), 
                    labels = label_date_short(),
                    limits =c(min(lim1), max(lim2)),
                    expand = c(0,0)) +
  theme_bw()+
  theme(axis.text.y=element_text(color="black",size=size_axis),
        axis.text.x=element_text(color="black",size=size_axis,angle=45,hjust=1),
        axis.title=element_text(size=size_axis_title),
        legend.text=element_text(size=size_legend),
        legend.title=element_text(size=size_legend_title),
        legend.position="bottom") +
  ggtitle("Preterm birth risk, for women <32yo and first parities")

plot_PTB_below32
```

# Above or equal to 32 yo
```{r}
m_PTB_bam_above32 <- bam(PTB~ s(BW) + s(birth_Y_M_num) + s(month, bs="cc") + s(mean_ssep2) + s(mean_Alt_mean2) + sex + Urban3 + Language + mother_nationality_cat2 + civil_status3 + HW + GR + COVID_first_wave + COVID_second_wave, family="binomial", data=bevn_eco_in7_above_32) 
summary(m_PTB_bam_above32)
plot(m_PTB_bam_above32, trans = plogis, select=1, shift = coef(m_PTB_bam_above32)[1], shade = TRUE, shade.col = "lightblue") #BW
plot(m_PTB_bam_above32, trans = plogis, select=2, ylim=c(0.01, 0.03), shift = coef(m_PTB_bam_above32)[1], shade = TRUE, shade.col = "lightblue") #time
  plot(m_PTB_bam_above32, trans = plogis, select=3, ylim=c(0.015, 0.025), shift = coef(m_PTB_bam_above32)[1], shade = TRUE, shade.col = "lightblue") #month
    plot(m_PTB_bam_above32, trans = plogis, select=4, ylim=c(0.0005, 0.025), shift = coef(m_PTB_bam_above32)[1], shade = TRUE, shade.col = "lightblue") #ssep
  plot(m_PTB_bam_above32, trans = plogis, select=5, ylim=c(0.0005, 0.025), shift = coef(m_PTB_bam_above32)[1], shade = TRUE, shade.col = "lightblue") #altitude
    plot_m_PTB_above_32 <- GAM_plot_function_binary(m_PTB_bam_above32, 2) # time
```

# Graph time variable
```{r}
x_date <-   bevn_eco_in7_below32 %>% #careful, mayhave to change the dataset if I later work with smaller time ranges!
  select(birth_Y_M, birth_Y_M_num) %>%
  distinct(birth_Y_M, .keep_all = TRUE) %>%
  rename(x=birth_Y_M_num)

plot_data_PTB_above32 <- plot_m_PTB_above_32  %>%
  mutate(x=round(x,0)) %>%
  left_join(x_date) %>%
  mutate(date_x= ymd(paste0(birth_Y_M,"-01")))
lim1 <- as.POSIXct(ymd("2007-01-01"))
lim2 <- as.POSIXct(ymd("2021-12-01"))

plot_PTB_above32 <- ggplot(data=plot_data_PTB_above32)+
  geom_line(aes(x=as.POSIXct(date_x),y=fit),lwd=lwdline, color=("#9557DC"))+
  geom_ribbon(aes(x=as.POSIXct(date_x),ymin=CIl,ymax=CIu),alpha=0.15,lwd=lwdline, fill='#69D8F3')+
  xlab("Timeline (years)")+
  ylab("Preterm birth probability")+
  scale_colour_manual('PTB', values =c("#9557DC"))+
  scale_fill_manual('PTB', values =c("#9557DC"))+
   scale_x_datetime( breaks = date_breaks("12 month"), 
                    labels = label_date_short(),
                    limits =c(min(lim1), max(lim2)),
                    expand = c(0,0)) +
  theme_bw()+
  theme(axis.text.y=element_text(color="black",size=size_axis),
        axis.text.x=element_text(color="black",size=size_axis,angle=45,hjust=1),
        axis.title=element_text(size=size_axis_title),
        legend.text=element_text(size=size_legend),
        legend.title=element_text(size=size_legend_title),
        legend.position="bottom") +
  ggtitle("Preterm birth risk, for women >=32yo and first parities")

plot_PTB_above32
```
