---
title: "SB GAM stratified by Maternal Nationality"
author: "Mathilde Le Vu"
date:  "`r Sys.Date()`"
html_document: 
output:
  rmdformats::robobook:
    code_folding: show
    self_contained: true
    highlight: pygments
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Swiss Mothers

```{r}
m_SB_bam_Swiss <- bam(stillbirth ~ s(GA_weeks) + s(mat_age) + s(birth_Y_M_num) + s(month, bs="cc") + s(mean_ssep2) + s(mean_Alt_mean2) + sex + Urban3 + Language + civil_status3 + HW + GR + COVID_first_wave + COVID_second_wave, family="binomial", data=bevn_eco_in6_Swiss)  
summary(m_SB_bam_Swiss)

  plot(m_SB_bam_Swiss, trans = plogis, select=1, shift = coef(m_SB_bam_Swiss)[1], shade = TRUE, shade.col = "lightblue") #GA
  plot(m_SB_bam_Swiss, trans = plogis, select=2, ylim=c(0, 0.003), shift = coef(m_SB_bam_Swiss)[1], shade = TRUE, shade.col = "lightblue") #mat age
    plot(m_SB_bam_Swiss, trans = plogis, select=3, ylim=c(0.0007, 0.0012), shift = coef(m_SB_bam_Swiss)[1], shade = TRUE, shade.col = "lightblue") #time
  plot(m_SB_bam_Swiss, trans = plogis, select=4, ylim=c(0.001, 0.001), shift = coef(m_SB_bam_Swiss)[1], shade = TRUE, shade.col = "lightblue") #month
    plot(m_SB_bam_Swiss, trans = plogis, select=5, ylim=c(0.0004, 0.002), shift = coef(m_SB_bam_Swiss)[1], shade = TRUE, shade.col = "lightblue") #sep
  plot(m_SB_bam_Swiss, trans = plogis, select=6, ylim=c(0.0004, 0.004), shift = coef(m_SB_bam_Swiss)[1], shade = TRUE, shade.col = "lightblue") #altitude
  
  k.check(m_SB_bam_Swiss) 
  concurvity(m_SB_bam_Swiss)
```

```{r}
#table to show OR, confidence interval and Cohen's d
  OR <- exp(coef(m_SB_bam_Swiss))
  beta <- coef(m_SB_bam_Swiss)
  Vb <- vcov(m_SB_bam_Swiss, unconditional = TRUE)
  se <- sqrt(diag(Vb))
  lci <- exp(beta-1.96*se)
  uci <- exp(beta+1.96*se)
  d <- abs(beta)/1.81
  my.ci_m_SB_bam_Swiss <- data.frame(cbind(OR, lci, uci, d))
  round(head(my.ci_m_SB_bam_Swiss, 10), 2)
```

# African

```{r}
m_SB_bam_Afr <- bam(stillbirth ~ s(GA_weeks) + s(mat_age) + s(birth_Y_M_num) + s(month, bs="cc") + s(mean_ssep2) + s(mean_Alt_mean2)+ sex + Urban3 + Language + civil_status3 + HW + GR + COVID_first_wave + COVID_second_wave, family="binomial", data=bevn_eco_in6_Afr)  
summary(m_SB_bam_Afr)

  plot(m_SB_bam_Afr, trans = plogis, select=1, shift = coef(m_SB_bam_Afr)[1], shade = TRUE, shade.col = "lightblue") #GA
  plot(m_SB_bam_Afr, trans = plogis, select=2, ylim=c(0, 0.007), shift = coef(m_SB_bam_Afr)[1], shade = TRUE, shade.col = "lightblue") #mat age
  plot(m_SB_bam_Afr, trans = plogis, select=3, ylim=c(0.0007, 0.003), shift = coef(m_SB_bam_Afr)[1], shade = TRUE, shade.col = "lightblue") #time
plot(m_SB_bam_Afr, trans = plogis, select=4, ylim=c(0.001, 0.003), shift = coef(m_SB_bam_Afr)[1], shade = TRUE, shade.col = "lightblue") #month
    plot(m_SB_bam_Afr, trans = plogis, select=5, ylim=c(0.0004, 0.004), shift = coef(m_SB_bam_Afr)[1], shade = TRUE, shade.col = "lightblue") #sep
  plot(m_SB_bam_Afr, trans = plogis, select=6, ylim=c(0.0004, 0.02), shift = coef(m_SB_bam_Afr)[1], shade = TRUE, shade.col = "lightblue") #altitude
  
  k.check(m_SB_bam_Afr) 
  concurvity(m_SB_bam_Afr)
```

```{r}
#table to show OR, confidence interval and Cohen's d
  OR <- exp(coef(m_SB_bam_Afr))
  beta <- coef(m_SB_bam_Afr)
  Vb <- vcov(m_SB_bam_Afr, unconditional = TRUE)
  se <- sqrt(diag(Vb))
  lci <- exp(beta-1.96*se)
  uci <- exp(beta+1.96*se)
  d <- abs(beta)/1.81
  my.ci_m_SB_bam_Afr <- data.frame(cbind(OR, lci, uci, d))
  round(head(my.ci_m_SB_bam_Afr, 10), 2)
```

# Asian

```{r}
m_SB_bam_As <- bam(stillbirth ~ s(GA_weeks) + s(mat_age) + s(birth_Y_M_num) + s(month, bs="cc") + s(mean_ssep2) + s(mean_Alt_mean2)+ sex + Urban3 + Language + civil_status3 + HW + GR + COVID_first_wave + COVID_second_wave, family="binomial", data=bevn_eco_in6_Asi)  
summary(m_SB_bam_As)

  plot(m_SB_bam_As, trans = plogis, select=1, shift = coef(m_SB_bam_As)[1], shade = TRUE, shade.col = "lightblue") #GA
  plot(m_SB_bam_As, trans = plogis, select=2, ylim=c(0, 0.003), shift = coef(m_SB_bam_As)[1], shade = TRUE, shade.col = "lightblue") #mat age
  plot(m_SB_bam_As, trans = plogis, select=3, ylim=c(0.001, 0.001), shift = coef(m_SB_bam_As)[1], shade = TRUE, shade.col = "lightblue") #time
  plot(m_SB_bam_As, trans = plogis, select=4, ylim=c(0.0005, 0.0018), shift = coef(m_SB_bam_As)[1], shade = TRUE, shade.col = "lightblue") #month
    plot(m_SB_bam_As, trans = plogis, select=5, ylim=c(0.0001, 0.0025), shift = coef(m_SB_bam_As)[1], shade = TRUE, shade.col = "lightblue") #sep
  plot(m_SB_bam_As, trans = plogis, select=6, ylim=c(0.0004, 0.009), shift = coef(m_SB_bam_As)[1], shade = TRUE, shade.col = "lightblue") #altitude
  
  k.check(m_SB_bam_As) 
  concurvity(m_SB_bam_As)
```

```{r}
#table to show OR, confidence interval and Cohen's d
  OR <- exp(coef(m_SB_bam_As))
  beta <- coef(m_SB_bam_As)
  Vb <- vcov(m_SB_bam_As, unconditional = TRUE)
  se <- sqrt(diag(Vb))
  lci <- exp(beta-1.96*se)
  uci <- exp(beta+1.96*se)
  d <- abs(beta)/1.81
  my.ci_m_SB_bam_As <- data.frame(cbind(OR, lci, uci, d))
  round(head(my.ci_m_SB_bam_As, 10), 2)
```

# European (non-Swiss)

```{r}
m_SB_bam_Eur <- bam(stillbirth ~ s(GA_weeks) + s(mat_age) + s(birth_Y_M_num) + s(month, bs="cc") + s(mean_ssep2) + s(mean_Alt_mean2)+ sex + Urban3 + Language + civil_status3 + HW + GR + COVID_first_wave + COVID_second_wave, family="binomial", data=bevn_eco_in6_Eur)  
summary(m_SB_bam_Eur)

  plot(m_SB_bam_Eur, trans = plogis, select=1, shift = coef(m_SB_bam_Eur)[1], shade = TRUE, shade.col = "lightblue") #GA
  plot(m_SB_bam_Eur, trans = plogis, select=2, ylim=c(0, 0.003), shift = coef(m_SB_bam_Eur)[1], shade = TRUE, shade.col = "lightblue") #mat age
    plot(m_SB_bam_Eur, trans = plogis, select=3, ylim=c(0.001, 0.001), shift = coef(m_SB_bam_Eur)[1], shade = TRUE, shade.col = "lightblue") #time
  plot(m_SB_bam_Eur, trans = plogis, select=4, ylim=c(0.0005, 0.0012), shift = coef(m_SB_bam_Eur)[1], shade = TRUE, shade.col = "lightblue") #month
    plot(m_SB_bam_Eur, trans = plogis, select=5, ylim=c(0.0004, 0.002), shift = coef(m_SB_bam_Eur)[1], shade = TRUE, shade.col = "lightblue") #sep
  plot(m_SB_bam_Eur, trans = plogis, select=6, ylim=c(0.0004, 0.002), shift = coef(m_SB_bam_Eur)[1], shade = TRUE, shade.col = "lightblue") #altitude
  
  k.check(m_SB_bam_Eur) 
  concurvity(m_SB_bam_Eur)
```

```{r}
#table to show OR, confidence interval and Cohen's d
  OR <- exp(coef(m_SB_bam_Eur))
  beta <- coef(m_SB_bam_Eur)
  Vb <- vcov(m_SB_bam_Eur, unconditional = TRUE)
  se <- sqrt(diag(Vb))
  lci <- exp(beta-1.96*se)
  uci <- exp(beta+1.96*se)
  d <- abs(beta)/1.81
  my.ci_m_SB_bam_Eur <- data.frame(cbind(OR, lci, uci, d))
  round(head(my.ci_m_SB_bam_Eur, 10), 2)
```

# Nothern American

```{r}
m_SB_bam_Nort_Am <- bam(stillbirth ~ s(GA_weeks) + s(mat_age) + s(birth_Y_M_num) + s(month, bs="cc") + s(mean_ssep2) + s(mean_Alt_mean2) + sex + Urban3 + Language + civil_status3 + HW + GR + COVID_first_wave + COVID_second_wave, family="binomial", data=bevn_eco_in6_Nort_Am)  
summary(m_SB_bam_Nort_Am)

  plot(m_SB_bam_Nort_Am, trans = plogis, select=1, shift = coef(m_SB_bam_Nort_Am)[1], shade = TRUE, shade.col = "lightblue") #GA
  plot(m_SB_bam_Nort_Am, trans = plogis, select=2, ylim=c(0, 0.008), shift = coef(m_SB_bam_Nort_Am)[1], shade = TRUE, shade.col = "lightblue") #mat age
    plot(m_SB_bam_Nort_Am, trans = plogis, select=3, ylim=c(0.0001, 0.004), shift = coef(m_SB_bam_Nort_Am)[1], shade = TRUE, shade.col = "lightblue") #time
  plot(m_SB_bam_Nort_Am, trans = plogis, select=4, ylim=c(0.0006, 0.0012), shift = coef(m_SB_bam_Nort_Am)[1], shade = TRUE, shade.col = "lightblue") #month
    plot(m_SB_bam_Nort_Am, trans = plogis, select=5, ylim=c(0.0004, 0.002), shift = coef(m_SB_bam_Nort_Am)[1], shade = TRUE, shade.col = "lightblue") #sep
  plot(m_SB_bam_Nort_Am, trans = plogis, select=6, ylim=c(0.0002, 0.004), shift = coef(m_SB_bam_Nort_Am)[1], shade = TRUE, shade.col = "lightblue") #altitude
  
  k.check(m_SB_bam_Nort_Am) 
  concurvity(m_SB_bam_Nort_Am)
```

```{r}
#table to show OR, confidence interval and Cohen's d
  OR <- exp(coef(m_SB_bam_Nort_Am))
  beta <- coef(m_SB_bam_Nort_Am)
  Vb <- vcov(m_SB_bam_Nort_Am, unconditional = TRUE)
  se <- sqrt(diag(Vb))
  lci <- exp(beta-1.96*se)
  uci <- exp(beta+1.96*se)
  d <- abs(beta)/1.81
  my.ci_m_SB_bam_Nort_Am <- data.frame(cbind(OR, lci, uci, d))
  round(head(my.ci_m_SB_bam_Nort_Am, 10), 2)
```

# Southern/Central American

```{r}
m_SB_bam_S_C_Am <- bam(stillbirth ~ s(GA_weeks) + s(mat_age) + s(birth_Y_M_num) + s(month, bs="cc") + s(mean_ssep2) + s(mean_Alt_mean2) + sex + Urban3 + Language + civil_status3 + HW + GR + COVID_first_wave + COVID_second_wave, family="binomial", data=bevn_eco_in6_S_C_Am)  
summary(m_SB_bam_S_C_Am)

  plot(m_SB_bam_S_C_Am, trans = plogis, select=1, shift = coef(m_SB_bam_S_C_Am)[1], shade = TRUE, shade.col = "lightblue") #GA
  plot(m_SB_bam_S_C_Am, trans = plogis, select=2, ylim=c(0, 0.003), shift = coef(m_SB_bam_S_C_Am)[1], shade = TRUE, shade.col = "lightblue") #mat age
    plot(m_SB_bam_S_C_Am, trans = plogis, select=3, ylim=c(0.0005, 0.005), shift = coef(m_SB_bam_S_C_Am)[1], shade = TRUE, shade.col = "lightblue") #time
  plot(m_SB_bam_S_C_Am, trans = plogis, select=4, ylim=c(0.0005, 0.0015), shift = coef(m_SB_bam_S_C_Am)[1], shade = TRUE, shade.col = "lightblue") #month
    plot(m_SB_bam_S_C_Am, trans = plogis, select=5, ylim=c(0.0004, 0.002), shift = coef(m_SB_bam_S_C_Am)[1], shade = TRUE, shade.col = "lightblue") #sep
  plot(m_SB_bam_S_C_Am, trans = plogis, select=6, ylim=c(0.0004, 0.002), shift = coef(m_SB_bam_S_C_Am)[1], shade = TRUE, shade.col = "lightblue") #altitude
  
  k.check(m_SB_bam_S_C_Am) 
  concurvity(m_SB_bam_S_C_Am)
```

```{r}
#table to show OR, confidence interval and Cohen's d
  OR <- exp(coef(m_SB_bam_S_C_Am))
  beta <- coef(m_SB_bam_S_C_Am)
  Vb <- vcov(m_SB_bam_S_C_Am, unconditional = TRUE)
  se <- sqrt(diag(Vb))
  lci <- exp(beta-1.96*se)
  uci <- exp(beta+1.96*se)
  d <- abs(beta)/1.81
  my.ci_m_SB_bam_S_C_Am <- data.frame(cbind(OR, lci, uci, d))
  round(head(my.ci_m_SB_bam_S_C_Am, 10), 2)
```
