---
title: "GAM_Covid"
author: "Mathilde Le Vu"
date:  "`r Sys.Date()`"
html_document: 
output:
  rmdformats::robobook:
    code_folding: show
    self_contained: true
    highlight: pygments
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Effect of having delivery date during the pandemic (wave 1 or 2)
Data: all births 2015-2021

```{r}
m_BW_bam_covid<- bam(BW ~ s(GA_weeks) +  s(mat_age) + s(birth_Y_M_num) + s(month, bs="cc") + s(mean_ssep2) + s(mean_Alt_mean2)  +parity_cat + sex + Urban3 + Language + mother_nationality_cat2 + civil_status3 + HW + COVID_first_wave + COVID_second_wave, data=bevn_eco_in7_15_21) 
summary(m_BW_bam_covid)
gam.check(m_BW_bam_covid) 
  
  plot(m_BW_bam_covid, select=1, ylim=c(0, 4000),shade = TRUE, shade.col = "lightblue",  shift = coef(m_BW_bam_covid)[1]) # GA weeks
  plot(m_BW_bam_covid, select=2, ylim=c(3200, 3400),shade = TRUE, shade.col = "lightblue",  shift = coef(m_BW_bam_covid)[1]) #maternal age
  plot(m_BW_bam_covid, select=3, ylim=c(3300, 3380),shade = TRUE, shade.col = "lightblue",  shift = coef(m_BW_bam_covid)[1],  xlab  = "100: 2015-04,    120: 2016-12, 140: 2018-08, 160: 2020-04, 180 : 2021-12")
  plot(m_BW_bam_covid, select=4, ylim=c(3340, 3380),shade = TRUE, shade.col = "lightblue",  shift = coef(m_BW_bam_covid)[1]) # month
  plot(m_BW_bam_covid, select=5, ylim=c(3200, 3400),shade = TRUE, shade.col = "lightblue",  shift = coef(m_BW_bam_covid)[1]) #ssep
    plot(m_BW_bam_covid, select=6, ylim=c(3100, 3500),shade = TRUE, shade.col = "lightblue",  shift = coef(m_BW_bam_covid)[1]) #altitude
    
  beta <- coef(m_BW_bam_covid)
  Vb <- vcov(m_BW_bam_covid, unconditional = TRUE)
  se <- sqrt(diag(Vb))
  n <- 585024
  d <- (abs(beta)/(sqrt(n)*se))
  my.ci <- data.frame(cbind(beta, lci = beta-1.96*se, uci = beta + 1.96*se, d))
  round(head(my.ci,17), 2)
```

# Effect of being infected during each specific trimester
Data: all births 2015-2021
```{r}
m_BW_bam_covid_trimester <- bam(BW ~ s(GA_weeks) +  s(mat_age) + s(birth_Y_M_num) + s(month, bs="cc") + s(mean_ssep2) + s(mean_Alt_mean2)+ parity_cat + sex + Urban3 + Language + mother_nationality_cat2 + civil_status3 + HW + COVID_first_trimester + COVID_second_trimester + COVID_third_trimester, data=bevn_eco_in7_15_21) 
summary(m_BW_bam_covid_trimester)

gam.check(m_BW_bam_covid_trimester) 
  
  plot(m_BW_bam_covid_trimester, select=1, ylim=c(0, 4000),shade = TRUE, shade.col = "lightblue",  shift =  coef(m_BW_bam_covid_trimester)[1]) # GA weeks
  plot(m_BW_bam_covid_trimester, select=2, ylim=c(3200, 3400),shade = TRUE, shade.col = "lightblue",  shift = coef(m_BW_bam_covid_trimester)[1]) #maternal age
  plot(m_BW_bam_covid_trimester, select=3, ylim=c(3300, 3380),shade = TRUE, shade.col = "lightblue",  shift = coef(m_BW_bam_covid_trimester)[1],  xlab  = "100: 2015-04,    120: 2016-12, 140: 2018-08, 160: 2020-04, 180 : 2021-12")
  plot(m_BW_bam_covid_trimester, select=4, ylim=c(3340, 3380),shade = TRUE, shade.col = "lightblue",  shift = coef(m_BW_bam_covid_trimester)[1]) # month
  plot(m_BW_bam_covid_trimester, select=5, ylim=c(3200, 3400),shade = TRUE, shade.col = "lightblue",  shift = coef(m_BW_bam_covid_trimester)[1]) #ssep
    plot(m_BW_bam_covid_trimester, select=6, ylim=c(3100, 3500),shade = TRUE, shade.col = "lightblue",  shift = coef(m_BW_bam_covid_trimester)[1]) #altitude
    
  beta <- coef(m_BW_bam_covid_trimester)
  Vb <- vcov(m_BW_bam_covid_trimester, unconditional = TRUE)
  se <- sqrt(diag(Vb))
  n <- 585024
  d <- (abs(beta)/(sqrt(n)*se))
  my.ci <- data.frame(cbind(beta, lci = beta-1.96*se, uci = beta + 1.96*se, d))
  round(head(my.ci,17), 2)
```

# Effect of being infected during two trimesters (1+3) vs of one trimester only.
Data: only COVID cases (so 2020-21). Not month and time variables-
```{r}
m_BW_bam_covid_two_trimesters <- bam(BW ~ s(GA_weeks) +  s(mat_age) + s(mean_ssep2) + s(mean_Alt_mean2)+ parity_cat + sex + Urban3 + Language + mother_nationality_cat2 + civil_status3 + COVID_two_trimesters, data=bevn_eco_in7_COVID_exp_during_pregnancy) 
summary(m_BW_bam_covid_two_trimesters)

gam.check(m_BW_bam_covid_two_trimesters) 
  
  plot(m_BW_bam_covid_two_trimesters, select=1, ylim=c(0, 4100),shade = TRUE, shade.col = "lightblue",  shift =  coef(m_BW_bam_covid_two_trimesters)[1]) # GA weeks
  plot(m_BW_bam_covid_two_trimesters, select=2, ylim=c(3300, 3450),shade = TRUE, shade.col = "lightblue",  shift = coef(m_BW_bam_covid_two_trimesters)[1]) #maternal age
  plot(m_BW_bam_covid_two_trimesters, select=3, ylim=c(3100, 3400),shade = TRUE, shade.col = "lightblue",  shift = coef(m_BW_bam_covid_two_trimesters)[1]) #ssep
    plot(m_BW_bam_covid_two_trimesters, select=4, ylim=c(3100, 3400),shade = TRUE, shade.col = "lightblue",  shift = coef(m_BW_bam_covid_two_trimesters)[1]) #altitude
    
  beta <- coef(m_BW_bam_covid_two_trimesters)
  Vb <- vcov(m_BW_bam_covid_two_trimesters, unconditional = TRUE)
  se <- sqrt(diag(Vb))
  n <- 127888
  d <- (abs(beta)/(sqrt(n)*se))
  my.ci <- data.frame(cbind(beta, lci = beta-1.96*se, uci = beta + 1.96*se, d))
  round(head(my.ci,15), 2)
```

