---
title: "Untitled"
author: "Graphs BW PTB SB univ"
date: "2023-08-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# BW

```{r include=FALSE}
m_BW_bam_univ <- bam(BW ~ s(birth_Y_M_num), data=bevn_eco_in7) 
plot_m_BW_univ_time <- GAM_plot_function_continuous(m_BW_bam_univ, 1) %>%
  mutate(model="unadjusted")
```


```{r}
x_date <-   bevn_eco_in7 %>% #careful, mayhave to change the dataset if I later work with smaller time ranges!
  select(birth_Y_M, birth_Y_M_num) %>%
  distinct(birth_Y_M, .keep_all = TRUE) %>%
  rename(x=birth_Y_M_num)

plot_data_BW_univ_not_adj_GA <- plot_m_BW_univ_time %>%
  mutate(x=round(x,0)) %>%
  left_join(x_date) %>%
  mutate(date_x= ymd(paste0(birth_Y_M,"-01")))

# graph parameters
lim1 <- as.POSIXct(ymd("2007-01-01"))
lim2 <- as.POSIXct(ymd("2022-12-01"))

plot_BW_univ_unadj_GA <- ggplot(data=plot_data_BW_univ_not_adj_GA)+
  geom_line(aes(x=as.POSIXct(date_x),y=fit),lwd=lwdline)+
  geom_ribbon(aes(x=as.POSIXct(date_x),ymin=CIl,ymax=CIu),alpha=0.15,lwd=lwdline)+
  xlab("Timeline (years)")+
  ylab("Birthweight (g)")+
  coord_cartesian(ylim=c(3200,3450)) +
  scale_colour_manual(                      values ="black")+
  scale_x_datetime( breaks = date_breaks("12 month"), 
                    labels = label_date_short(),
                    limits =c(as.POSIXct("2007-01-01"), max(lim2)),
                    expand = c(0,0)) +
  theme_bw()+
  theme(axis.text.y=element_text(color="black",size=size_axis),
        axis.text.x=element_text(color="black",size=size_axis,angle=45,hjust=1),
        axis.title=element_text(size=size_axis_title),
        legend.text=element_text(size=size_legend),
        legend.title=element_text(size=size_legend_title),
        legend.position="bottom",
        legend.key.width = unit(1.5, "cm"), 
        legend.key.height = unit(0.5, "cm")) +
        theme(axis.title.x = axis.title.x.position)
plot_BW_univ_unadj_GA
```

# PTB
```{r include=FALSE}
m_PTB_bam_univ <- bam(PTB~ s(birth_Y_M_num), family="binomial", data=bevn_eco_in7) 
m_PTB_bam_univ <- GAM_plot_function_binary(m_PTB_bam_univ, 1)
```

```{r}
x_date <-   bevn_eco_in7 %>% 
  select(birth_Y_M, birth_Y_M_num) %>%
  distinct(birth_Y_M, .keep_all = TRUE) %>%
  rename(x=birth_Y_M_num)

plot_data_PTB_univ <- m_PTB_bam_univ %>%
  mutate(x=round(x,0)) %>%
  left_join(x_date) %>%
  mutate(date_x= ymd(paste0(birth_Y_M,"-01")))

plot_PTB_univ_unadj_BW <- ggplot(data=plot_data_PTB_univ)+
  geom_line(aes(x=as.POSIXct(date_x),y=fit),lwd=lwdline)+
  geom_ribbon(aes(x=as.POSIXct(date_x),ymin=CIl,ymax=CIu),alpha=0.15,lwd=lwdline)+
  xlab("Timeline (years)")+
  ylab("Preterm birth probability")+
  coord_cartesian(ylim=c(0.03,0.07)) +
 scale_colour_manual(values ="black")+
  scale_x_datetime( breaks = date_breaks("12 month"), 
                    labels = label_date_short(),
                    limits =c(as.POSIXct("2007-01-01"), max(lim2)),
                    expand = c(0,0)) +
  theme_bw()+
  theme(axis.text.y=element_text(color="black",size=size_axis),
        axis.text.x=element_text(color="black",size=size_axis,angle=45,hjust=1),
        axis.title=element_text(size=size_axis_title),
        legend.text=element_text(size=size_legend),
        legend.title=element_text(size=size_legend_title),
        legend.position="bottom",
        legend.key.width = unit(1.5, "cm"), 
        legend.key.height = unit(0.5, "cm")) +
        theme(axis.title.x = axis.title.x.position)
plot_PTB_univ_unadj_BW
```

# Stillbirth
```{r include=FALSE}
m_SB_bam_univ <- bam(stillbirth~ s(birth_Y_M_num), family="binomial", data=bevn_eco_in6)
plot_m_SB_bam_univ <- GAM_plot_function_binary(m_SB_bam_univ, 1)
```


```{r}
x_date <-   bevn_eco_in6 %>% 
  select(birth_Y_M, birth_Y_M_num) %>%
  distinct(birth_Y_M, .keep_all = TRUE) %>%
  rename(x=birth_Y_M_num)

plot_data_SB_univ <- plot_m_SB_bam_univ %>%
  mutate(x=round(x,0)) %>%
  left_join(x_date) %>%
  mutate(date_x= ymd(paste0(birth_Y_M,"-01")))

plot_SB_univ <- ggplot(data=plot_data_SB_univ)+
  geom_line(aes(x=as.POSIXct(date_x),y=fit),lwd=lwdline)+
  geom_ribbon(aes(x=as.POSIXct(date_x),ymin=CIl,ymax=CIu),alpha=0.15,lwd=lwdline)+
  xlab("Timeline (years)")+
  ylab("Stillbirth probability")+
  coord_cartesian(ylim=c(0.0030,0.0050)) +
  scale_colour_manual(values ="black")+
  scale_x_datetime( breaks = date_breaks("1 year"), 
                    labels = label_date_short(),
                    limits =c(as.POSIXct("2007-01-01"), max(lim2)),
                    expand = c(0,0)) +
  theme_bw()+
  theme(axis.text.y=element_text(color="black",size=size_axis),
        axis.text.x=element_text(color="black",size=size_axis,angle=45,hjust=1),
        axis.title=element_text(size=size_axis_title),
        legend.text=element_text(size=size_legend),
        legend.title=element_text(size=size_legend_title),
        legend.position="bottom",
        legend.key.width = unit(1.5, "cm"), 
        legend.key.height = unit(0.5, "cm")) +
        theme(axis.title.x = axis.title.x.position)
plot_SB_univ
```