---
title: "Gam model: Lowbirth weight, normal and macrosomia"
author: "Mathilde Le Vu"
date:  "`r Sys.Date()`"
html_document: 
output:
  rmdformats::robobook:
    code_folding: show
    self_contained: true
    highlight: pygments
editor_options: 
  chunk_output_type: console
---

# LBW
## 2007-2020
```{r}
m_LBW_bam <-bam(LBW~s(GA_weeks)+ s(mat_age) + s(birth_Y_M_num) + s(month) +s(mean_ssep2) + Urban3 + parity_cat + Language + mother_nationality_cat2,family="binomial", data=bevn_eco_in7)
  summary(m_LBW_bam)
    plot(m_LBW_bam, trans = plogis, select=1, ylim=c(0, 1), shift = coef(m_LBW_bam)[1], shade = TRUE, shade.col = "lightblue") #GA_weeks
  plot(m_LBW_bam, trans = plogis, select=2, ylim=c(.005, .03), shift = coef(m_LBW_bam)[1], shade = TRUE, shade.col = "lightblue") #mat_age
  plot(m_LBW_bam, trans = plogis, select=3, ylim=c(.010, .020), shift = coef(m_LBW_bam)[1], shade = TRUE, shade.col = "lightblue") #birth_Y_M_num
    plot(m_LBW_bam, trans = plogis, select=4, ylim=c(0.012, 0.017), shift = coef(m_LBW_bam)[1], shade = TRUE, shade.col = "lightblue") #month
  plot(m_LBW_bam, trans = plogis, select=5, ylim=c(.005, .025), shift = coef(m_LBW_bam)[1], shade = TRUE, shade.col = "lightblue") #ssep

    #setting month as linear term
  m_LBW_bam_2 = update(m_LBW_bam, . ~ . - s(month) + month)
  summary(m_LBW_bam_2)
  plot(m_LBW_bam_2, trans = plogis, select=1, ylim=c(0, 1), shift = coef(m_LBW_bam_2)[1], shade = TRUE, shade.col = "lightblue") #GA_weeks
  plot(m_LBW_bam_2, trans = plogis, select=2, ylim=c(.005, .03), shift = coef(m_LBW_bam_2)[1], shade = TRUE, shade.col = "lightblue") #mat_age
  plot(m_LBW_bam_2, trans = plogis, select=3, ylim=c(.01, .02), shift = coef(m_LBW_bam_2)[1], shade = TRUE, shade.col = "lightblue") #birth_Y_M_num
  plot(m_LBW_bam_2, trans = plogis, select=4, ylim=c(.005, .025), shift = coef(m_LBW_bam_2)[1], shade = TRUE, shade.col = "lightblue") #ssep
  
  k.check(m_LBW_bam_2)
  concurvity(m_LBW_bam_2)
  
  #to calculate the OR of LBW for non smooth terms
  OR <- exp(coef(m_LBW_bam_2))
  beta <- coef(m_LBW_bam_2)
  Vb <- vcov(m_LBW_bam_2, unconditional = TRUE)
  se <- sqrt(diag(Vb))
  lci <- exp(beta-1.96*se)
  uci <- exp(beta+1.96*se)
  d <- abs(beta)/1.81
  my.ci <- data.frame(cbind(OR, lci, uci, d))
  round(head(my.ci, 14), 2)
```

## 2008-2010
```{r}
  m_LBW_bam_2009 <-bam(LBW~s(GA_weeks)+ s(mat_age) + s(birth_Y_M_num) + s(month) + s(mean_ssep2) + parity_cat + Urban3 + Language + mother_nationality_cat2,family="binomial", data=bevn_eco_in7_2008_10)
  summary(m_LBW_bam_2009)
  k.check(m_LBW_bam_2009)
  concurvity(m_LBW_bam_2009)
  
  #birth_Y_M_num and month too correlated : do the model without month.
  #birth_Y_M_num and mean_ssep2 set as non smooth variables (edf ~1)
   m_LBW_bam_2009_2 <-bam(LBW~s(GA_weeks)+ s(mat_age) + birth_Y_M_num + mean_ssep2 + parity_cat + Urban3 + Language + mother_nationality_cat2,family="binomial", data=bevn_eco_in7_2008_10)
    summary(m_LBW_bam_2009_2)
  plot(m_LBW_bam_2009_2, trans = plogis, select=1, ylim=c(0, 1), shift = coef(m_LBW_bam_2009_2)[1], shade = TRUE, shade.col = "lightblue") #GA_weeks
  plot(m_LBW_bam_2009_2, trans = plogis, select=2, ylim=c(.005, .04), shift = coef(m_LBW_bam_2009_2)[1], shade = TRUE, shade.col = "lightblue") #mat_age
  k.check(m_LBW_bam_2009_2)
  concurvity(m_LBW_bam_2009_2)

  #to calculate the OR of LBW for non smooth terms
  OR <- exp(coef(m_LBW_bam_2009_2))
  beta <- coef(m_LBW_bam_2009_2)
  Vb <- vcov(m_LBW_bam_2009_2, unconditional = TRUE)
  se <- sqrt(diag(Vb))
  lci <- exp(beta-1.96*se)
  uci <- exp(beta+1.96*se)
  d <- abs(beta)/1.81
  my.ci <- data.frame(cbind(OR, lci, uci, d))
  round(head(my.ci, 15), 2)
```

## 2017-2020
```{r}
  m_LBW_bam_covid <-bam(LBW~s(GA_weeks)+ s(mat_age) + s(birth_Y_M_num) +s(mean_ssep2) + parity_cat + Urban3 + Language + mother_nationality_cat2,family="binomial", data=bevn_eco_in7_2017_20)
  summary(m_LBW_bam_covid)
  
  plot(m_LBW_bam_covid, trans = plogis, select=1, ylim=c(0, 1), shift = coef(m_LBW_bam_covid)[1], shade = TRUE, shade.col = "lightblue") #GA_weeks
  plot(m_LBW_bam_covid, trans = plogis, select=2, ylim=c(.005, .04), shift = coef(m_LBW_bam_covid)[1], shade = TRUE, shade.col = "lightblue") #mat_age
  plot(m_LBW_bam_covid, trans = plogis, select=3, ylim=c(.005, .015), shift = coef(m_LBW_bam_covid)[1], shade = TRUE, shade.col = "lightblue") #birth_Y_M_num
  plot(m_LBW_bam_covid, trans = plogis, select=4, ylim=c(.005, .02), shift = coef(m_LBW_bam_covid)[1], shade = TRUE, shade.col = "lightblue") #ssep
  
  k.check(m_LBW_bam_covid)
  concurvity(m_LBW_bam_covid)
  
  #we can lower k value of birth_Y_M_num because its almost linear (edf=1.99), and set ssep as linear term
  m_LBW_bam_covid_2 <-bam(LBW~s(GA_weeks)+ s(mat_age) + s(birth_Y_M_num, k=3) + mean_ssep2 + parity_cat + Urban3 + Language +  mother_nationality_cat2,family="binomial", data=bevn_eco_in7_2017_20)
  summary(m_LBW_bam_covid_2)
  
  plot(m_LBW_bam_covid_2, trans = plogis, select=1, ylim=c(0, 1), shift = coef(m_LBW_bam_covid_2)[1], shade = TRUE, shade.col = "lightblue") #GA_weeks
  plot(m_LBW_bam_covid_2, trans = plogis, select=2, ylim=c(.005, .06), shift = coef(m_LBW_bam_covid_2)[1], shade = TRUE, shade.col = "lightblue") #mat_age
  plot(m_LBW_bam_covid_2, trans = plogis, select=3, ylim=c(.015, .025), shift = coef(m_LBW_bam_covid_2)[1], shade = TRUE, shade.col = "lightblue") #birth_Y_M_num
  k.check(m_LBW_bam_covid_2)
  concurvity(m_LBW_bam_covid_2)
  
  #to calculate the OR of LBW for non smooth terms
  OR <- exp(coef(m_LBW_bam_covid_2))
  beta <- coef(m_LBW_bam_covid_2)
  Vb <- vcov(m_LBW_bam_covid_2, unconditional = TRUE)
  se <- sqrt(diag(Vb))
  lci <- exp(beta-1.96*se)
  uci <- exp(beta+1.96*se)
  d <- abs(beta)/1.81
  my.ci <- data.frame(cbind(OR, lci, uci, d))
  round(head(my.ci, 14), 2)
```

## BW ordered: LBW (<2.5kg), normal BW (2.5-4kg), macro (>4kg)
```{r}
 # m_BW_ordered <- bam(BW_ordered ~ s(GA_weeks) +  s(mat_age, k=7) + s(birth_Y_M_num) + s(month) + s(mean_ssep2) + parity_cat + sex + Urban3 + Language + mother_nationality_cat2, family=ocat(R=3),data=bevn_eco_in7)
 # summary(m_BW_ordered)
      
  #plot(m_BW_ordered,select=1, ylim=c(-20, 10), shift = coef(m_BW_ordered)[1], shade = TRUE, shade.col = "lightblue") #GA weeks
   #   plot(m_BW_ordered,select=2, ylim=c(1, 4), shift = coef(m_BW_ordered)[1], shade = TRUE, shade.col = "lightblue") #mat age
    #  plot(m_BW_ordered,select=3, ylim=c(1, 4), shift = coef(m_BW_ordered)[1], shade = TRUE, shade.col = "lightblue") #time
     #   plot(m_BW_ordered,select=4, ylim=c(1, 4), shift = coef(m_BW_ordered)[1], shade = TRUE, shade.col = "lightblue") #month
      #plot(m_BW_ordered,select=5, ylim=c(1, 4), shift = coef(m_BW_ordered)[1], shade = TRUE, shade.col = "lightblue") #ssep

      #k.check(m_BW_ordered)
      #gam.check(m_BW_ordered)
      # with trans = plogis??
```
 
## Multinomial  - lowbirthweight 

```{r}
#bevn_eco_in7$BW_cat3 <- relevel(bevn_eco_in7$BW_cat3=="2")
#  m_BW_multinom <- bam(BW_cat3 ~ s(GA_weeks) +  s(mat_age, k=7) + s(birth_Y_M_num) + s(month) + s(mean_ssep2) + parity_cat + sex + Urban3 + Language + mother_nationality_cat2, family=multinom(K=3),data=bevn_eco_in7)
 #   m_BW_multinom <- gam(BW_cat3 ~ s(GA_weeks) +  s(mat_age, k=7) + s(birth_Y_M_num) + s(month) + s(mean_ssep2) + parity_cat + sex + Urban3 + Language + mother_nationality_cat2, family=multinom(K=2),data=bevn_eco_in7)
    
  #  b <- gam(list(y~s(x1)+s(x2),~s(x1)+s(x2)),family=multinom(K=2))

   # m_BW_multinom <- gam(list(BW_cat3 ~ s(GA_weeks) +  s(mat_age, k=7) + s(birth_Y_M_num) + s(month) + s(mean_ssep2) + parity_cat + sex + Urban3 + Language + mother_nationality_cat2), family=multinom(K=2),data=bevn_eco_in7)
```


# LBW vs "Normal" birthweight
## 2007-2020
```{r}
m_LBW_normal_bam <-bam(LBW_norm~s(GA_weeks)+ s(mat_age) + s(birth_Y_M_num) + s(month) +s(mean_ssep2) + parity_cat + Urban3 + Language + mother_nationality_cat2,family="binomial", data=bevn_eco_in7)
  summary(m_LBW_normal_bam)

#month as linear variable
  m_LBW_normal_bam_2 <-bam(LBW_norm~s(GA_weeks)+ s(mat_age) + s(birth_Y_M_num) + month +s(mean_ssep2) + parity_cat + Urban3 + Language + mother_nationality_cat2,family="binomial", data=bevn_eco_in7)
  summary(m_LBW_normal_bam_2)
  
  plot(m_LBW_normal_bam_2, trans = plogis, select=1, ylim=c(0, 1), shift = coef(m_LBW_normal_bam_2)[1], shade = TRUE, shade.col = "lightblue") #GA_weeks
  plot(m_LBW_normal_bam_2, trans = plogis, select=2, ylim=c(.005, .03), shift = coef(m_LBW_normal_bam_2)[1], shade = TRUE, shade.col = "lightblue") #mat_age
  plot(m_LBW_normal_bam_2, trans = plogis, select=3, ylim=c(.005, .025), shift = coef(m_LBW_normal_bam_2)[1], shade = TRUE, shade.col = "lightblue") #birth_Y_M_num
  plot(m_LBW_normal_bam_2, trans = plogis, select=4, ylim=c(.005, .030), shift = coef(m_LBW_normal_bam_2)[1], shade = TRUE, shade.col = "lightblue") #ssep
  
  k.check(m_LBW_normal_bam_2)
  concurvity(m_LBW_normal_bam_2)
  
  #to calculate the OR of LBW vs normal BW 
  OR <- exp(coef(m_LBW_normal_bam_2))
  beta <- coef(m_LBW_normal_bam_2)
  Vb <- vcov(m_LBW_normal_bam_2, unconditional = TRUE)
  se <- sqrt(diag(Vb))
  lci <- exp(beta-1.96*se)
  uci <- exp(beta+1.96*se)
  d <- abs(beta)/1.81
  my.ci <- data.frame(cbind(OR, lci, uci, d))
  round(head(my.ci, 14), 2)
```


## 2008-2010
```{r}
m_LBW_normal_bam_2009 <-bam(LBW_norm~s(GA_weeks)+ s(mat_age) + s(birth_Y_M_num) + s(mean_ssep2) + parity_cat + Urban3 + Language + mother_nationality_cat2,family="binomial", data=bevn_eco_in7_2008_10)
summary(m_LBW_normal_bam_2009)

  plot(m_LBW_normal_bam_2009, trans = plogis, select=1, ylim=c(0, 1), shift = coef(m_LBW_normal_bam_2009)[1], shade = TRUE, shade.col = "lightblue") #GA_weeks
  plot(m_LBW_normal_bam_2009, trans = plogis, select=2, ylim=c(.005, .03), shift = coef(m_LBW_normal_bam_2009)[1], shade = TRUE, shade.col = "lightblue") #mat_age
  plot(m_LBW_normal_bam_2009, trans = plogis, select=3, ylim=c(.005, .025), shift = coef(m_LBW_normal_bam_2009)[1], shade = TRUE, shade.col = "lightblue") #birth_Y_M_num
  plot(m_LBW_normal_bam_2009, trans = plogis, select=4, ylim=c(.010, .03), shift = coef(m_LBW_normal_bam_2009)[1], shade = TRUE, shade.col = "lightblue") #ssep
  
  #set birth_Y_M_num and ssep variables as linear terms
m_LBW_normal_bam_2009_2 <-bam(LBW_norm~s(GA_weeks)+ s(mat_age) + birth_Y_M_num + mean_ssep2 + parity_cat + Urban3 + Language + mother_nationality_cat2,family="binomial", data=bevn_eco_in7_2008_10)
summary(m_LBW_normal_bam_2009_2)

  plot(m_LBW_normal_bam_2009_2, trans = plogis, select=1, ylim=c(0, 1), shift = coef(m_LBW_normal_bam_2009_2)[1], shade = TRUE, shade.col = "lightblue") #GA_weeks
  plot(m_LBW_normal_bam_2009_2, trans = plogis, select=2, ylim=c(.005, .05), shift = coef(m_LBW_normal_bam_2009_2)[1], shade = TRUE, shade.col = "lightblue") #mat_age
k.check(m_LBW_normal_bam_2009_2)
concurvity(m_LBW_normal_bam_2009_2)

  #to calculate the OR of LBW vs normal BW 
  OR <- exp(coef(m_LBW_normal_bam_2009_2))
  beta <- coef(m_LBW_normal_bam_2009_2)
  Vb <- vcov(m_LBW_normal_bam_2009_2, unconditional = TRUE)
  se <- sqrt(diag(Vb))
  lci <- exp(beta-1.96*se)
  uci <- exp(beta+1.96*se)
  d <- abs(beta)/1.81
  my.ci <- data.frame(cbind(OR, lci, uci, d))
  round(head(my.ci, 15), 2)
```

## 2017-2020
```{r}
m_LBW_normal_bam_covid <-bam(LBW_norm~s(GA_weeks)+ s(mat_age) + s(birth_Y_M_num) +s(mean_ssep2) + parity_cat + Urban3 + Language + mother_nationality_cat2,family="binomial", data=bevn_eco_in7_2017_20)
summary(m_LBW_normal_bam_covid)

  plot(m_LBW_normal_bam_covid, trans = plogis, select=1, ylim=c(0, 1), shift = coef(m_LBW_normal_bam_covid)[1], shade = TRUE, shade.col = "lightblue") #GA_weeks
  plot(m_LBW_normal_bam_covid, trans = plogis, select=2, ylim=c(.005, .05), shift = coef(m_LBW_normal_bam_covid)[1], shade = TRUE, shade.col = "lightblue") #mat_age
  plot(m_LBW_normal_bam_covid, trans = plogis, select=3, ylim=c(.012, .018), shift = coef(m_LBW_normal_bam_covid)[1], shade = TRUE, shade.col = "lightblue") #birth_Y_M_num
  plot(m_LBW_normal_bam_covid, trans = plogis, select=4, ylim=c(.005, .03), shift = coef(m_LBW_normal_bam_covid)[1], shade = TRUE, shade.col = "lightblue") #ssep
  
  #setting ssep as linear variable (edf=1.62)
  m_LBW_normal_bam_covid_2 <-bam(LBW_norm~s(GA_weeks)+ s(mat_age) + s(birth_Y_M_num) + mean_ssep2 + parity_cat + Urban3 + Language + mother_nationality_cat2,family="binomial", data=bevn_eco_in7_2017_20)
summary(m_LBW_normal_bam_covid_2)

 plot(m_LBW_normal_bam_covid_2, trans = plogis, select=1, ylim=c(0, 1), shift = coef(m_LBW_normal_bam_covid_2)[1], shade = TRUE, shade.col = "lightblue") #GA_weeks
  plot(m_LBW_normal_bam_covid_2, trans = plogis, select=2, ylim=c(.005, .07), shift = coef(m_LBW_normal_bam_covid_2)[1], shade = TRUE, shade.col = "lightblue") #mat_age
  plot(m_LBW_normal_bam_covid_2, trans = plogis, select=3, ylim=c(.020, .028), shift = coef(m_LBW_normal_bam_covid_2)[1], shade = TRUE, shade.col = "lightblue") #birth_Y_M_num
  k.check(m_LBW_normal_bam_covid)
  concurvity(m_LBW_normal_bam_covid)
  
#to calculate the OR of LBW vs normal BW 
  OR <- exp(coef(m_LBW_normal_bam_covid_2))
  beta <- coef(m_LBW_normal_bam_covid_2)
  Vb <- vcov(m_LBW_normal_bam_covid_2, unconditional = TRUE)
  se <- sqrt(diag(Vb))
  lci <- exp(beta-1.96*se)
  uci <- exp(beta+1.96*se)
  d <- abs(beta)/1.81
  my.ci <- data.frame(cbind(OR, lci, uci, d))
  round(head(my.ci, 14), 2)
```

# Macrosomia vs "normal" birthweight
## 2007-2020
```{r}
m_macro_normal_bam <-bam(macro_norm~s(GA_weeks)+ s(mat_age) + s(birth_Y_M_num) + s(month) +s(mean_ssep2) + parity_cat + Urban3 + Language + mother_nationality_cat2,family="binomial", data=bevn_eco_in7)
summary(m_macro_normal_bam)

plot(m_macro_normal_bam, trans = plogis, select=1, ylim=c(0, 0.6), shift = coef(m_macro_normal_bam)[1], shade = TRUE, shade.col = "lightblue") #GA_weeks
  plot(m_macro_normal_bam, trans = plogis, select=2, ylim=c(0.03, 0.06), shift = coef(m_macro_normal_bam)[1], shade = TRUE, shade.col = "lightblue") #mat_age
  plot(m_macro_normal_bam, trans = plogis, select=3, ylim=c(0.045, 0.055), shift = coef(m_macro_normal_bam)[1], shade = TRUE, shade.col = "lightblue") #birth_Y_M_num
    plot(m_macro_normal_bam, trans = plogis, select=4, ylim=c(0.045, 0.052), shift = coef(m_macro_normal_bam)[1], shade = TRUE, shade.col = "lightblue") #month
  plot(m_macro_normal_bam, trans = plogis, select=5, ylim=c(0.02, 0.06), shift = coef(m_macro_normal_bam)[1], shade = TRUE, shade.col = "lightblue") #ssep

  k.check(m_macro_normal_bam)
  concurvity(m_macro_normal_bam)
  
#to calculate the OR of Macrosomia vs normal BW 
  OR <- exp(coef(m_macro_normal_bam))
  beta <- coef(m_macro_normal_bam)
  Vb <- vcov(m_macro_normal_bam, unconditional = TRUE)
  se <- sqrt(diag(Vb))
  lci <- exp(beta-1.96*se)
  uci <- exp(beta+1.96*se)
  d <- abs(beta)/1.81
  my.ci <- data.frame(cbind(OR, lci, uci, d))
  round(head(my.ci, 13), 2)
```
 
 
## 2008-2010
```{r}
m_macro_normal_bam_2009 <-bam(macro_norm~s(GA_weeks)+ s(mat_age) + s(birth_Y_M_num) +s(mean_ssep2) + parity_cat + Urban3 + Language + mother_nationality_cat2,family="binomial", data=bevn_eco_in7_2008_10)
summary(m_macro_normal_bam_2009)

plot(m_macro_normal_bam_2009, trans = plogis, select=1, ylim=c(0, 0.8), shift = coef(m_macro_normal_bam_2009)[1], shade = TRUE, shade.col = "lightblue") #GA_weeks
  plot(m_macro_normal_bam_2009, trans = plogis, select=2, ylim=c(0, 0.2), shift = coef(m_macro_normal_bam_2009)[1], shade = TRUE, shade.col = "lightblue") #mat_age
  plot(m_macro_normal_bam_2009, trans = plogis, select=3, ylim=c(0.04, 0.06), shift = coef(m_macro_normal_bam_2009)[1], shade = TRUE, shade.col = "lightblue") #birth_Y_M_num
    plot(m_macro_normal_bam_2009, trans = plogis, select=4, ylim=c(0.03, 0.1), shift = coef(m_macro_normal_bam_2009)[1], shade = TRUE, shade.col = "lightblue") #ssep

    #setting mat age and time variables as linear (edf= 1.005 and 1.378, respectively)
  m_macro_normal_bam_2009_2 <-bam(macro_norm~s(GA_weeks)+ s(mean_ssep2) + mat_age + birth_Y_M_num +parity_cat + Urban3 + Language + mother_nationality_cat2,family="binomial", data=bevn_eco_in7_2008_10)
  summary(m_macro_normal_bam_2009_2)
  
  plot(m_macro_normal_bam_2009_2, trans = plogis, select=1, ylim=c(0, 0.8), shift = coef(m_macro_normal_bam_2009)[1], shade = TRUE, shade.col = "lightblue") #GA_weeks
    plot(m_macro_normal_bam_2009_2, trans = plogis, select=2, ylim=c(0.03, 0.06), shift = coef(m_macro_normal_bam_2009)[1], shade = TRUE, shade.col = "lightblue") #ssep
  
  k.check(m_macro_normal_bam_2009_2)
  concurvity(m_macro_normal_bam_2009_2)
  
#to calculate the OR of Macrosomia vs normal BW 
  OR <- exp(coef(m_macro_normal_bam_2009_2))
  beta <- coef(m_macro_normal_bam_2009_2)
  Vb <- vcov(m_macro_normal_bam_2009_2, unconditional = TRUE)
  se <- sqrt(diag(Vb))
  lci <- exp(beta-1.96*se)
  uci <- exp(beta+1.96*se)
  d <- abs(beta)/1.81
  my.ci <- data.frame(cbind(OR, lci, uci, d))
  round(head(my.ci, 15), 2)
```

## 2017-2020
```{r}
m_macro_normal_bam_covid <-bam(macro_norm~s(GA_weeks)+ s(mat_age) + s(birth_Y_M_num) +s(mean_ssep2) + parity_cat + Urban3 + Language + mother_nationality_cat2,family="binomial", data=bevn_eco_in7_2017_20)
summary(m_macro_normal_bam_covid)

plot(m_macro_normal_bam_covid, trans = plogis, select=1, ylim=c(0, 0.7), shift = coef(m_macro_normal_bam_covid)[1], shade = TRUE, shade.col = "lightblue") #GA_weeks
  plot(m_macro_normal_bam_covid, trans = plogis, select=2, ylim=c(0.02, 0.08), shift = coef(m_macro_normal_bam_covid)[1], shade = TRUE, shade.col = "lightblue") #mat_age
  plot(m_macro_normal_bam_covid, trans = plogis, select=3, ylim=c(0.04, 0.06), shift = coef(m_macro_normal_bam_covid)[1], shade = TRUE, shade.col = "lightblue") #birth_Y_M_num
    plot(m_macro_normal_bam_covid, trans = plogis, select=4, ylim=c(0.02, 0.06), shift = coef(m_macro_normal_bam_covid)[1], shade = TRUE, shade.col = "lightblue") #ssep

  k.check(m_macro_normal_bam_covid)
  concurvity(m_macro_normal_bam_covid)
  
#to calculate the OR of Macrosomia vs normal BW 
  OR <- exp(coef(m_macro_normal_bam_covid))
  beta <- coef(m_macro_normal_bam_covid)
  Vb <- vcov(m_macro_normal_bam_covid, unconditional = TRUE)
  se <- sqrt(diag(Vb))
  lci <- exp(beta-1.96*se)
  uci <- exp(beta+1.96*se)
  d <- abs(beta)/1.81
  my.ci <- data.frame(cbind(OR, lci, uci, d))
  round(head(my.ci, 13), 2)
```
 