---
title: "gam lbw"
author: "Mathilde Le Vu"
date: "2024-02-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Low birth weight
```{r echo=FALSE}
#model used in the paper
m_LBW_crises <- bam(LBW ~s(mat_age) + birth_Y_M_num + s(month, bs="cc") + mean_ssep2_by_10 + mean_Alt_mean2_by_100+  parity_cat + sex +Urban3 + Language + mother_nationality_cat2 + civil_status3+  HW + GR_relativ_by_pregn_month  + covid_hosp_relativ_by_pregn_month, family="binomial", data=bevn_eco_in7)

# extracting the plot information
plot_m_LBW_main_mat_age <- GAM_plot_function_binary(m_LBW_crises, 1)
plot_m_LBW_main_month <- GAM_plot_function_binary(m_LBW_crises, 2)
```

## Graph maternal age X LBW

```{r}
plot_LBW_main_mat_age <- ggplot(data=plot_m_LBW_main_mat_age)+
  geom_line(aes(x=(x),y=fit),lwd=lwdline, color=("black"))+
  geom_ribbon(aes(x=(x),ymin=CIl,ymax=CIu),alpha=0.15,lwd=lwdline, fill='black')+
  xlab("Maternal age (years)")+
  ylab("Low birth weight probability")+
  theme_bw()+
  coord_cartesian(ylim=c(0.05,0.15)) +
  theme(axis.text.y=element_text(color="black",size=size_axis),
        axis.text.x=element_text(color="black",size=size_axis,angle=45,hjust=1),
        axis.title=element_text(size=size_axis_title),
        legend.text=element_text(size=size_legend),
        legend.title=element_text(size=size_legend_title),
        legend.position="bottom") +
  scale_x_continuous(breaks=seq(0,60,by=5),expand = c(0, 0)) +
  theme(axis.title.x = axis.title.x.position)
plot_LBW_main_mat_age
```


## Graph seasonality X LBW 
```{r}
plot_LBW_main_seasonality <- ggplot(data=plot_m_LBW_main_month)+
  geom_line(aes(x=(x),y=fit),lwd=lwdline, color=("black"))+
  geom_ribbon(aes(x=(x),ymin=CIl,ymax=CIu),alpha=0.15,lwd=lwdline, fill='black')+
  xlab("Month")+
  ylab("Low birth weight probability")+
  theme_bw()+
  coord_cartesian(ylim=c(0.05,0.15)) +
  theme(axis.text.y=element_text(color="black",size=size_axis),
        axis.text.x=element_text(color="black",size=size_axis,angle=45,hjust=1),
        axis.title=element_text(size=size_axis_title),
        legend.text=element_text(size=size_legend),
        legend.title=element_text(size=size_legend_title),
        legend.position="bottom") +
  scale_x_continuous(breaks=seq(1,12,by=1),expand = c(0, 0)) +
  theme(axis.title.x = axis.title.x.position)
plot_LBW_main_seasonality
```

## Table summarizing the preterm birth outcome model
### Without the intercept but with the pvalue
```{r}
m_LBW_crises <- bam(LBW ~s(mat_age)  + s(month, bs="cc")+HW + GR_relativ_by_pregn_month  + covid_hosp_relativ_by_pregn_month+ birth_Y_M_num + mean_ssep2_by_10 + mean_Alt_mean2_by_100+  parity_cat + sex +Urban3 + Language + mother_nationality_cat2 + civil_status3, family="binomial", data=bevn_eco_in7)

OR <- exp(coef(m_LBW_crises))
beta <- coef(m_LBW_crises)
Vb <- vcov(m_LBW_crises , unconditional = TRUE)
se <- sqrt(diag(Vb))
lci <- exp(beta-1.96*se)
uci <- exp(beta+1.96*se)
d <- abs(beta)/1.81
my.ci <- data.frame(cbind(OR, lci, uci, d))
tab_LBW_bam <- format(round((my.ci[2:20,]), 2), nsmall=2)

tab_LBW_crises <-tab_LBW_bam %>%
  mutate(OR=as.character(OR),
         lci=as.character(lci),
         uci=as.character(uci),
         d=as.character(d))

tab_LBW_crises['Variable'] <- c("Heatwave (ref: 0)", "Great Recession (continuous)",
                                "COVID (continuous)",
                                "Time (by month)","SSEP (/10 points)",
                                "Altitude (/100m)","Parity (ref: 1)", " ", " ", 
                                "Sex (ref: male)", "Urban (ref: rural)",
                                "Language region (ref: German)", " ", 
                                "Maternal nationality (ref: Swiss)", " ", " ",
                                " ", " ",
                                "Civil status (ref: married)"
)

tab_LBW_crises['Category'] <- c("1", "","",
                                " "," "," ",
                                "2", "3", ">3", "Female",
                                "Urban", "French", "Italian",
                                "Africa", "Asia", "Europe", "Northern America",
                                "Southern/Central America",
                                "Single")
tab_LBW_crises<-tab_LBW_crises[, c('Variable', "Category", "OR", "lci","uci", "d")]



pvalue_non_smooth_m_LBW = summary(m_LBW_crises)
pvalue_non_smooth_m_LBW <- pvalue_non_smooth_m_LBW$p.table[2:20, "Pr(>|z|)"]
pvalue_non_smooth_m_LBW <- format(pvalue_non_smooth_m_LBW, scientific=FALSE)
pvalues_non_smooth_LBW_main_df <- data.frame(pvalue_non_smooth_m_LBW)%>%
  rename(pvalues_smooth_LBW_main=pvalue_non_smooth_m_LBW)

pvalues_non_smooth_LBW_main_df['Variable'] <- c("Heatwave (ref: 0)",
                                                "Great Recession (continuous)",
                                                "COVID (continuous)",
                                                "Time (by month)", "SSEP (/10 points)",
                                                "Altitude (/100m)",
                                                "Parity (ref: 1)", " ", " ", 
                                                "Sex (ref: male)", "Urban (ref: rural)",
                                                "Language region (ref: German)", " ", 
                                                "Maternal nationality (ref: Swiss)", " ", " ",
                                                " ", " ",
                                                "Civil status (ref: married)"
)
pvalues_non_smooth_LBW_main_df['Category'] <- c( "1", "","",
                                                 " "," "," ",
                                                 "2", "3", ">3", "Female", "Urban", "French", "Italian", 
                                                 "Africa", "Asia", "Europe", "Northern America",
                                                 "Southern/Central America", "Single")
pvalues_non_smooth_LBW_main_df <- pvalues_non_smooth_LBW_main_df %>%
  rename(c(pvalue=(pvalues_smooth_LBW_main)))%>%
  mutate(pvalue=as.numeric(pvalue)) %>%
  mutate(pvalue1=pvalue)

pvalues_non_smooth_LBW_main_df$pvalue <-  format(round(pvalues_non_smooth_LBW_main_df$pvalue, digits=2), nsmall=2)

pvalues_non_smooth_LBW_main_df <- pvalues_non_smooth_LBW_main_df %>%
  mutate(pvalue1=case_when((pvalue1<0.00001) ~ "<0.0001",
                           (pvalue1<0.001)~ "<0.001",
                           (pvalue1<0.01)~ "<0.01")) 

pvalues_non_smooth_LBW_main_df$pvalue1 <- (ifelse(is.na(pvalues_non_smooth_LBW_main_df$pvalue1), 
                                                  pvalues_non_smooth_LBW_main_df$pvalue, pvalues_non_smooth_LBW_main_df$pvalue1))
pvalues_non_smooth_LBW_main_df1 <- pvalues_non_smooth_LBW_main_df %>%
  select(-one_of('pvalue')) %>%
  rename("pvalue"="pvalue1") 

LBW <- tab_LBW_crises %>%
  full_join(pvalues_non_smooth_LBW_main_df1)  

# p values smooth variables
pvalues_smooth_LBW_main = summary(m_LBW_crises)
pvalues_smooth_LBW_main <- pvalues_smooth_LBW_main$s.table[,4]
pvalues_smooth_LBW_main <- format(pvalues_smooth_LBW_main, scientific=FALSE)

pvalues_smooth_LBW_main_df <- data.frame(pvalues_smooth_LBW_main) %>%
  dplyr::mutate(Variable=c("Maternal age (years)", "Seasonality (month)")) %>%
  rename(c(pvalue=(pvalues_smooth_LBW_main)))%>%
  mutate(pvalue=as.numeric(pvalue)) %>%
  mutate(pvalue1=pvalue) %>%
  add_column(OR="")%>%
  add_column(Category="")%>%
  add_column(lci="") %>%
  add_column(uci="")%>%
  add_column(d="")


pvalues_smooth_LBW_main_df$pvalue <-  format(round(pvalues_smooth_LBW_main_df$pvalue, digits=2), nsmall=2)

pvalues_smooth_LBW_main_df <- pvalues_smooth_LBW_main_df %>%
  mutate(pvalue1=case_when((pvalue1<0.00001) ~ "<0.0001",
                           (pvalue1<0.001)~ "<0.001",
                           (pvalue1<0.01)~ "<0.01")) 

pvalues_smooth_LBW_main_df$pvalue1 <- (ifelse(is.na(pvalues_smooth_LBW_main_df$pvalue1), 
                                              pvalues_smooth_LBW_main_df$pvalue, pvalues_smooth_LBW_main_df$pvalue1))


pvalues_smooth_LBW_main_df <- pvalues_smooth_LBW_main_df%>%
  select(-one_of('pvalue')) %>%
  rename("pvalue"="pvalue1") 
pvalues_smooth_LBW_main_df<-pvalues_smooth_LBW_main_df[, c('Variable', "Category", "OR", "lci","uci", "d", "pvalue")]

rowinfo = c("Smooth variables", "","", "", "", "", "")
ow <- rbind(rowinfo,pvalues_smooth_LBW_main_df)

LBW_full <- rbind(LBW, ow)

LBW_main_gt <- LBW_full %>%
  gt()%>%
  # tab_header(title=md(gt::html("**Table 3 : Association between the risk of low birth weight and <br> neonatal, maternal and ecological factors from a GAM (model 2.1)**"))) %>%
  tab_spanner(label = "95% CI", columns = c(lci, uci)) %>%
  tab_options(table.width = pct(30), data_row.padding = px(1),   table.font.size = 12,
              column_labels.font.weight = "bold",  row_group.font.weight  = "bold",
              heading.title.font.size = 14, heading.subtitle.font.size = 14,
              source_notes.font.size = 12) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_body(rows = 20)) %>%
  tab_source_note(source_note = "n=1,263,853")
LBW_main_gt

LBW_estimates_main_gt <- LBW_main_gt%>%
  gtsave(here("output/tables_for_paper/suppl_material", "LBW_estimates_categ_and_smooth_gt_with_pvalue.html"))
LBW_estimates_main_gt <- LBW_main_gt%>%
  gtsave(here("output/tables_for_paper/suppl_material", "LBW_estimates_categ_and_smooth_gt_with_pvalue.docx"))
```


# Univariate model
```{r include=FALSE}
m_LBW_bam_univ <- bam(LBW~ s(birth_Y_M_num), family="binomial", data=bevn_eco_in7) 
m_LBW_bam_univ_graph <- GAM_plot_function_binary(m_LBW_bam_univ, 1)
```

```{r}
# graph parameters
lim1 <- as.POSIXct(ymd("2007-01-01"))
lim2 <- as.POSIXct(ymd("2022-12-01"))

x_date <-   bevn_eco_in7 %>% 
  select(birth_Y_M, birth_Y_M_num) %>%
  distinct(birth_Y_M, .keep_all = TRUE) %>%
  rename(x=birth_Y_M_num)

plot_data_LBW_univ <- m_LBW_bam_univ_graph %>%
  mutate(x=round(x,0)) %>%
  left_join(x_date) %>%
  mutate(date_x= ymd(paste0(birth_Y_M,"-01")))

plot_LBW_univ <- ggplot(data=plot_data_LBW_univ)+
  geom_line(aes(x=as.POSIXct(date_x),y=fit),lwd=lwdline)+
  geom_ribbon(aes(x=as.POSIXct(date_x),ymin=CIl,ymax=CIu),alpha=0.15,lwd=lwdline)+
  xlab("Timeline (years)")+
  ylab("Low birth weight probability")+
  coord_cartesian(ylim=c(0.03,0.06)) +
 scale_colour_manual(values ="black")+
  scale_x_datetime( breaks = date_breaks("1 year"), 
                    labels = label_date_short(),
                    limits =c(as.POSIXct("2007-01-01"), max(lim2)),
                    expand = c(0,0)) +
  theme_bw()+
  theme(axis.text.y=element_text(color="black",size=size_axis),
        axis.text.x=element_text(color="black",size=size_axis,angle=45,hjust=1),
        axis.title=element_text(size=size_axis_title),
        legend.text=element_text(size=size_legend),
        legend.title=element_text(size=size_legend_title),
        legend.position="bottom",
        legend.key.width = unit(1.5, "cm"), 
        legend.key.height = unit(0.5, "cm")) +
        theme(axis.title.x = axis.title.x.position)
plot_LBW_univ
```

# Stratified models
# Socio economic position : by SSEP tertile
```{r include=FALSE}
m_LBW_bam_L_SSEP1_2 <- bam(LBW ~ s(birth_Y_M_num), family="binomial", data=bevn_eco_in7_L_SSEP1)  
m_LBW_bam_M_SSEP1_2 <- bam(LBW ~ s(birth_Y_M_num), family="binomial", data=bevn_eco_in7_M_SSEP1)  
m_LBW_bam_H_SSEP1_2 <- bam(LBW ~ s(birth_Y_M_num), family="binomial", data=bevn_eco_in7_H_SSEP1)

plot_m_LBW_bam_L_SSEP1_2 <- GAM_plot_function_binary(m_LBW_bam_L_SSEP1_2, 1) %>%
  mutate(SEP="low")
plot_m_LBW_bam_M_SSEP1_2 <- GAM_plot_function_binary(m_LBW_bam_M_SSEP1_2, 1) %>%
  mutate(SEP="medium")
plot_m_LBW_bam_H_SSEP1_2 <- GAM_plot_function_binary(m_LBW_bam_H_SSEP1_2, 1) %>%
  mutate(SEP="high")
```

```{r}
x_date <-   bevn_eco_in7 %>% #careful, mayhave to change the dataset if I later work with smaller time ranges!
  select(birth_Y_M, birth_Y_M_num) %>%
  distinct(birth_Y_M, .keep_all = TRUE) %>%
  rename(x=birth_Y_M_num)

plot_LBW_SEP2 <- plot_m_LBW_bam_L_SSEP1_2  %>%
  rbind(plot_m_LBW_bam_M_SSEP1_2) %>%
  rbind(plot_m_LBW_bam_H_SSEP1_2) %>%
  mutate(x=round(x,0)) %>%
  left_join(x_date) %>%
  mutate(date_x= ymd(paste0(birth_Y_M,"-01")))

ggplot_LBW_SEP2 <- ggplot(data=plot_LBW_SEP2)+
  geom_line(aes(x=as.POSIXct(date_x),y=fit,col=SEP, linetype=SEP),lwd=lwdline)+
  geom_ribbon(aes(x=as.POSIXct(date_x),ymin=CIl,ymax=CIu,fill=SEP),alpha=0.15,lwd=lwdline)+
  xlab("Timeline (years)")+
  ylab("Low birth weight probability")+
  coord_cartesian(ylim=c(0.03,0.07)) +
  # scale_colour_manual("",
  #                     values = c("#555555","#555555","#555555"),
  #                     limits=c("fitall","CIlall","CIuall"),
  #                     labels=c("fully adjusted","95% CI","95% CI"))+
  scale_colour_manual('SSEP',                                                #colour manual is for the line
                      limits=c("low","medium", "high"),
                      # labels=c("fully adjusted","95% CI","95% CI"),
                    values =c("darkorchid1","lightpink3", "darkmagenta"))+
  scale_fill_manual('SSEP',                                              # fill is for CI
                    limits=c("low","medium", "high"), 
                    # labels=c("fully adjusted","95% CI","95% CI"),  
                    values =c("darkorchid1","lightpink3", "darkmagenta"))+
  scale_x_datetime( breaks = date_breaks("1 year"), 
                    labels = label_date_short(),
                    limits =c(as.POSIXct("2007-01-01"), max(lim2)),
                    expand = c(0,0)) +
  scale_linetype_manual('SSEP',
                        limits = c("low", "medium", "high"),
                        values = c("solid", "dashed", "dotted")) +
    theme_bw()+
  theme(axis.text.y=element_text(color="black",size=10),
        axis.text.x=element_text(color="black",size=size_axis,angle=45,hjust=1),
        axis.title=element_text(size=size_axis_title),
        axis.title.y=element_text(size=14), # Decrease y-axis title font size
        legend.text=element_text(size=size_legend),
        legend.title=element_text(size=size_legend_title),
        legend.position="bottom",
        legend.key.width = unit(1.5, "cm"), 
        legend.key.height = unit(0.5, "cm")
        #,    panel.grid.major=element_line(colour = "black", linetype = "dotted"),
   # panel.grid.minor=element_line(colour = "black", linetype = "dotted")
   ) +
theme(axis.title.x = axis.title.x.position)
ggplot_LBW_SEP2
```

# By maternal nationality, adjusted for time only
```{r include=FALSE}
m_LBW_bam_swiss2 <- bam(LBW ~ s(birth_Y_M_num), family="binomial", data=bevn_eco_in7_Swiss)
m_LBW_bam_Afr2 <- bam(LBW ~ s(birth_Y_M_num), family="binomial", data=bevn_eco_in7_Afr)  
m_LBW_bam_Asi2 <- bam(LBW ~ s(birth_Y_M_num), family="binomial", data=bevn_eco_in7_Asi)  
m_LBW_bam_Eur2 <- bam(LBW ~ s(birth_Y_M_num), family="binomial", data=bevn_eco_in7_Eur)  
m_LBW_bam_Nort_Am2 <- bam(LBW ~ s(birth_Y_M_num), family="binomial", data=bevn_eco_in7_Nort_Am)  
m_LBW_bam_S_C_Am2 <- bam(LBW ~ s(birth_Y_M_num), family="binomial", data=bevn_eco_in7_S_C_Am)  

plot_m_LBW_bam_swiss2 <- GAM_plot_function_binary(m_LBW_bam_swiss2, 1) %>%
  mutate(nationality="Swiss")
plot_m_LBW_bam_Afr2 <- GAM_plot_function_binary(m_LBW_bam_Afr2, 1) %>%
  mutate(nationality="African")
plot_m_LBW_bam_Asi2 <- GAM_plot_function_binary(m_LBW_bam_Asi2, 1) %>%
  mutate(nationality="Asian")
plot_m_LBW_bam_Eur2 <- GAM_plot_function_binary(m_LBW_bam_Eur2, 1) %>%
  mutate(nationality="European")
plot_m_LBW_bam_Nort_Am2 <- GAM_plot_function_binary(m_LBW_bam_Nort_Am2, 1) %>%
  mutate(nationality="Northern American")
plot_m_LBW_bam_S_C_Am2 <- GAM_plot_function_binary(m_LBW_bam_S_C_Am2, 1) %>%
  mutate(nationality="Southern/Central American")
```

```{r}
plot_LBW_nationality2 <- plot_m_LBW_bam_swiss2 %>%
  rbind(plot_m_LBW_bam_Afr2) %>%
  rbind(plot_m_LBW_bam_Asi2) %>%
  rbind(plot_m_LBW_bam_Eur2) %>%
  rbind(plot_m_LBW_bam_Nort_Am2) %>%
  rbind(plot_m_LBW_bam_S_C_Am2) %>%
  mutate(x=round(x,0)) %>%
  left_join(x_date) %>%
  mutate(date_x= ymd(paste0(birth_Y_M,"-01")))

ggplot_LBW_nationality2 <- ggplot(data=plot_LBW_nationality2)+
  geom_line(aes(x=as.POSIXct(date_x),y=fit,col=nationality, linetype=nationality),lwd=lwdline)+
  geom_ribbon(aes(x=as.POSIXct(date_x),ymin=CIl,ymax=CIu,fill=nationality),alpha=0.15,lwd=lwdline)+
  xlab("Timeline (years)")+
  ylab("Low birth weight probability")+
  coord_cartesian(ylim=c(0.03,0.06)) +
  scale_colour_manual('Maternal nationality',
                      limits=c("Swiss","African", "Asian", "European", "Northern American", "Southern/Central American"),
                      values =c("#69D8F3","gold", "#8B0000", "hotpink", "lightgreen", "#666975"))+
  scale_fill_manual('Maternal nationality',
                    limits=c("Swiss","African", "Asian", "European", "Northern American", "Southern/Central American"),
                      values =c("#69D8F3","gold", "#8B0000", "hotpink", "lightgreen", "#666975"))+
  scale_x_datetime( breaks = date_breaks("1 year"), 
                    labels = label_date_short(),
                    limits =c(as.POSIXct("2007-01-01"), max(lim2)),
                    expand = c(0,0)) +
  scale_linetype_manual('Maternal nationality',
                        limits = c("Swiss", "African", "Asian", "European", "Northern American", "Southern/Central American"),
                        values = c("solid", "dashed", "dotted", "dotdash", "longdash", "twodash")) +
  theme_bw()+
  theme(axis.text.y=element_text(color="black",size=size_axis),
        axis.text.x=element_text(color="black",size=size_axis,angle=45,hjust=1),
        axis.title=element_text(size=size_axis_title),
        legend.text=element_text(size=size_legend),
        legend.title=element_text(size=size_legend_title),
        legend.position="bottom",
        legend.key.width = unit(1.5, "cm"), 
        legend.key.height = unit(0.5, "cm"))+
theme(axis.title.x = axis.title.x.position)
ggplot_LBW_nationality2
```

# By langage region, unadjusted for time only
```{r include=FALSE}
m_LBW_bam_German2<- bam(LBW ~ s(birth_Y_M_num), family="binomial", data=bevn_eco_in7_German) 
m_LBW_bam_French2<- bam(LBW ~ s(birth_Y_M_num), family="binomial", data=bevn_eco_in7_French)  
m_LBW_bam_Italian2<- bam(LBW ~ s(birth_Y_M_num), family="binomial", data=bevn_eco_in7_Italian)  
 
plot_m_LBW_bam_German2 <- GAM_plot_function_binary(m_LBW_bam_German2, 1) %>%
  mutate(language_region="German")
plot_m_LBW_bam_French2 <- GAM_plot_function_binary(m_LBW_bam_French2, 1) %>%
  mutate(language_region="French")
plot_m_LBW_bam_Italian2 <- GAM_plot_function_binary(m_LBW_bam_Italian2, 1) %>%
  mutate(language_region="Italian")
```

```{r}
plot_LBW_language2 <- plot_m_LBW_bam_German2 %>%
  rbind(plot_m_LBW_bam_French2) %>%
  rbind(plot_m_LBW_bam_Italian2) %>%
  mutate(x=round(x,0)) %>%
  left_join(x_date) %>%
  mutate(date_x= ymd(paste0(birth_Y_M,"-01")))

ggplot_LBW_Language_region2 <- ggplot(data=plot_LBW_language2)+
  geom_line(aes(x=as.POSIXct(date_x),y=fit,col=language_region, linetype=language_region),lwd=lwdline)+
  geom_ribbon(aes(x=as.POSIXct(date_x),ymin=CIl,ymax=CIu,fill=language_region),alpha=0.15,lwd=lwdline)+
  xlab("Timeline (years)")+
  ylab("Low birth weight probability")+
  coord_cartesian(ylim=c(0.03,0.06)) +
  scale_colour_manual('Language region',
                      limits=c("German","French", "Italian"),
                      values =c("aquamarine","cadetblue1", "aquamarine4"))+
  scale_fill_manual('Language region',
                    limits=c("German","French", "Italian"),
                      values =c("aquamarine","cadetblue1", "aquamarine4"))+
  scale_x_datetime( breaks = date_breaks("1 year"), 
                    labels = label_date_short(),
                    limits =c(as.POSIXct("2007-01-01"), max(lim2)),
                    expand = c(0,0)) +
  scale_linetype_manual('Language region',
                        limits = c("German", "French", "Italian"),
                        values = c("solid", "dashed", "dotted")) +
  theme_bw()+
  theme(axis.text.y=element_text(color="black",size=size_axis),
        axis.text.x=element_text(color="black",size=size_axis,angle=45,hjust=1),
        axis.title=element_text(size=size_axis_title),
        legend.text=element_text(size=size_legend),
        legend.title=element_text(size=size_legend_title),
        legend.position="bottom",
        legend.key.width = unit(1.5, "cm"), 
        legend.key.height = unit(0.5, "cm")) +
theme(axis.title.x = axis.title.x.position)
ggplot_LBW_Language_region2
```


# By sex
```{r include=FALSE}
m_LBW_males <- bam(LBW ~ s(birth_Y_M_num), family="binomial", data=bevn_eco_in7_males)  
m_LBW_females <- bam(LBW ~ s(birth_Y_M_num), family="binomial", data=bevn_eco_in7_females)  

plot_m_LBW_males <- GAM_plot_function_binary(m_LBW_males, 1) %>%
  mutate(Sex="Males")
plot_m_LBW_females <- GAM_plot_function_binary(m_LBW_females, 1) %>%
  mutate(Sex="Females")
```

```{r}
LBW_plot_data_sex <- plot_m_LBW_males %>%
  rbind(plot_m_LBW_females) %>%
  mutate(x=round(x,0)) %>%
  left_join(x_date) %>%
  mutate(date_x= ymd(paste0(birth_Y_M,"-01")))

plot_LBW_sex <- ggplot(data=LBW_plot_data_sex)+
  geom_line(aes(x=as.POSIXct(date_x),y=fit,col=Sex, linetype=Sex),lwd=lwdline)+
  geom_ribbon(aes(x=as.POSIXct(date_x),ymin=CIl,ymax=CIu,fill=Sex),alpha=0.15,lwd=lwdline)+
  xlab("Timeline (years)")+
  ylab("Low birth weight probability")+
  coord_cartesian(ylim=c(0.03, 0.06)) +
  scale_colour_manual('Sex',
                      limits=c("Males","Females"),
                      values =c("magenta","purple"))+
  scale_fill_manual('Sex',
                    limits=c("Males","Females"),
                      values =c("magenta","purple"))+
  scale_x_datetime( breaks = date_breaks("1 year"), 
                    labels = label_date_short(),
                    limits =c(as.POSIXct("2007-01-01"), max(lim2)),
                    expand = c(0,0)) +
  scale_linetype_manual('Sex',
                        limits = c("Males", "Females"),
                        values = c("solid", "dashed")) +
  theme_bw()+
  theme(axis.text.y=element_text(color="black",size=size_axis),
        axis.text.x=element_text(color="black",size=size_axis,angle=45,hjust=1),
        axis.title=element_text(size=size_axis_title),
        legend.text=element_text(size=size_legend),
        legend.title=element_text(size=size_legend_title),
        legend.position="bottom",
        legend.key.width = unit(1.5, "cm"), 
        legend.key.height = unit(0.5, "cm"))  +
        theme(axis.title.x = axis.title.x.position)
plot_LBW_sex
```
