---
title: "GAM interaction SSEP X language region"
author: "Mathilde Le Vu"
date:  "`r Sys.Date()`"
html_document: 
output:
  rmdformats::robobook:
    code_folding: show
    self_contained: true
    highlight: pygments
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### Model without interaction (for comparison)
```{r}
m_BW_bam5_2 <- bam(BW ~ s(GA_weeks) +  s(mat_age) + s(birth_Y_M_num) + s(month, bs="cc") + s(mean_ssep2) + s(mean_Alt_mean2)+ parity_cat + sex + Urban3 + Language + mother_nationality_cat2 + civil_status3 + HW + GR + COVID_first_wave + COVID_second_wave, data=bevn_eco_in7)  
  summary(m_BW_bam5_2)

  plot(m_BW_bam5_2, select=1, ylim=c(0, 4000),shade = TRUE, shade.col = "lightblue",  shift = coef(m_BW_bam5_2)[1]) #GA
  plot(m_BW_bam5_2, select=2, ylim=c(3200, 3400),shade = TRUE, shade.col = "lightblue",  shift = coef(m_BW_bam5_2)[1]) #mat age
  plot(m_BW_bam5_2, select=3, ylim=c(3300, 3380),shade = TRUE, shade.col = "lightblue",  shift = coef(m_BW_bam5_2)[1],  xlab  = "1 : 2007-01,     25: 2009-01,     50: 2011-02,    75: 2013-03,   100: 2015-04,    125: 2017-05, 150: 2019-06") #birth_Y_M_num
  plot(m_BW_bam5_2, select=4, ylim=c(3330, 3350),shade = TRUE, shade.col = "lightblue",  shift = coef(m_BW_bam5_2)[1]) #month
  plot(m_BW_bam5_2, select=5, ylim=c(3250, 3400),shade = TRUE, shade.col = "lightblue",  shift = coef(m_BW_bam5_2)[1]) #mean ssep
  plot(m_BW_bam5_2, select=6, ylim=c(3100, 3400),shade = TRUE, shade.col = "lightblue",  shift = coef(m_BW_bam5_2)[1]) #mean altitude

#getting the CI 95% and d
  beta <- coef(m_BW_bam5_2)
  Vb <- vcov(m_BW_bam5_2, unconditional = TRUE)
  se <- sqrt(diag(Vb))
  n <- 1184367
  d <- (abs(beta)/(sqrt(n)*se))
  my.ci <- data.frame(cbind(beta, lci = beta-1.96*se, uci = beta + 1.96*se, d))
  round(head(my.ci,18), 2)  
```

## Interaction SSEP and Language region

```{r}
  m_BW_bam_SEP_int_Lang <- bam(BW ~s(GA_weeks) + s(mat_age) + s(birth_Y_M_num) + s(month, bs="cc") +  s(mean_ssep2, by=Language) + s(mean_Alt_mean2)+ parity_cat + sex  +  Urban3 + Language + mother_nationality_cat2 + civil_status3 + HW + GR + COVID_first_wave + COVID_second_wave, data=bevn_eco_in7)
  summary(m_BW_bam_SEP_int_Lang)

  plot(m_BW_bam_SEP_int_Lang, select=1, ylim=c(0, 4000), shift= coef(m_BW_bam_SEP_int_Lang)[1], shade = TRUE, shade.col = "lightblue") #GA
  plot(m_BW_bam_SEP_int_Lang, select=2, ylim=c(3200, 3400),shade = TRUE, shade.col = "lightblue",  shift = coef(m_BW_bam_SEP_int_Lang)[1]) #mat age
  plot(m_BW_bam_SEP_int_Lang, select=3, ylim=c(3290, 3490),shade = TRUE, shade.col = "lightblue",  shift = coef(m_BW_bam_SEP_int_Lang)[1],  xlab  = "1 : 2007-01,     25: 2009-01,     50: 2011-02,    75: 2013-03,   100: 2015-04,    125: 2017-05, 150: 2019-06") #birth_Y_M_num
  plot(m_BW_bam_SEP_int_Lang, select=4, ylim=c(3330, 3350),shade = TRUE, shade.col = "lightblue",  shift = coef(m_BW_bam_SEP_int_Lang)[1]) #month
  plot(m_BW_bam_SEP_int_Lang, select=5, ylim=c(3100, 3450), shift = coef(m_BW_bam_SEP_int_Lang)[1], shade = TRUE, shade.col = "lightblue") #ssep * German language region
  plot(m_BW_bam_SEP_int_Lang, select=6, ylim=c(3100, 3450), shift = coef(m_BW_bam_SEP_int_Lang)[1], shade = TRUE, shade.col = "lightblue") #ssep* French language region
  plot(m_BW_bam_SEP_int_Lang, select=7, ylim=c(3100, 3450), shift = coef(m_BW_bam_SEP_int_Lang)[1], shade = TRUE, shade.col = "lightblue") #ssep * Italian language region
  plot(m_BW_bam_SEP_int_Lang, select=8, ylim=c(3100, 3400), shift = coef(m_BW_bam_SEP_int_Lang)[1], shade = TRUE, shade.col = "lightblue") 
  
  beta <- coef(m_BW_bam_SEP_int_Lang)
  Vb <- vcov(m_BW_bam_SEP_int_Lang, unconditional = TRUE)
  se <- sqrt(diag(Vb))
  n <- 1184367
  d <- (abs(beta)/(sqrt(n)*se))
  my.ci <- data.frame(cbind(beta, lci = beta-1.96*se, uci = beta + 1.96*se, d))
  round(head(my.ci, 18), 2) 
```

