---
title: "Gam model: gestational age"
author: "Mathilde Le Vu"
date:  "`r Sys.Date()`"
html_document: 
output:
  rmdformats::robobook:
    code_folding: show
    self_contained: true
    highlight: pygments
editor_options: 
  chunk_output_type: console
---

# Continuous GA in days

## 2007-2020
```{r}
m_GA_bam_days <- bam(GA_days ~ s(BW) +  s(mat_age) + s(birth_Y_M_num) + s(month) + s(mean_ssep2) + parity_cat + sex + Urban3 + mother_nationality_cat2 + Language, data=bevn_eco_in7)
summary(m_GA_bam_days)
  #plot(m_GA_bam_days, all.terms = TRUE,pages=1, shade = TRUE, shade.col = "lightblue")
  plot(m_GA_bam_days, select=1, shade = TRUE, shade.col = "lightblue",  shift = coef(m_GA_bam_days)[1]) #BW
  plot(m_GA_bam_days, select=2, ylim=c(265, 280),shade = TRUE, shade.col = "lightblue",  shift = coef(m_GA_bam_days)[1]) #mat age
  plot(m_GA_bam_days, select=3, ylim=c(274, 278),shade = TRUE, shade.col = "lightblue",  shift = coef(m_GA_bam_days)[1],  xlab  = "1 : 2007-01,     25: 2009-01,      50: 2011-02,     75: 2013-03,      100: 2015-04,      125: 2017-05,      150: 2019-06") #birth_Y_M_num
  plot(m_GA_bam_days, select=4, ylim=c(275, 277),shade = TRUE, shade.col = "lightblue",  shift = coef(m_GA_bam_days)[1]) #month
  plot(m_GA_bam_days, select=5, ylim=c(272, 280),shade = TRUE, shade.col = "lightblue",  shift = coef(m_GA_bam_days)[1]) #ssep

  #checking that residuals are not determined
  gam.check(m_GA_bam_days)
  concurvity(m_GA_bam_days, full=TRUE)
  
  #estimate, 95%CI and d
  beta <- coef(m_GA_bam_days)
  Vb <- vcov(m_GA_bam_days, unconditional = TRUE)
  se <- sqrt(diag(Vb))
  n <- 1099328
  d <- (abs(beta)/(sqrt(n)*se))
  my.ci <- data.frame(cbind(beta, lci = beta-1.96*se, uci = beta + 1.96*se, d))
  round(head(my.ci,14), 2)
  
  #without BW
  m_GA_bam <- bam(GA_days ~ s(mat_age) + s(birth_Y_M_num) + s(month) + s(mean_ssep2) + parity_cat + sex + Urban3 + mother_nationality_cat2 + Language, data=bevn_eco_in7)
  summary(m_GA_bam)
  concurvity(m_GA_bam, full=TRUE)
  gam.check(m_GA_bam)
```

## 2008-2010
```{r}
m_GA_bam_2009 <- bam(GA_days ~ s(BW) +  s(mat_age) + s(birth_Y_M_num) + s(mean_ssep2) + parity_cat + sex + Urban3 + mother_nationality_cat2 + Language, data=bevn_eco_in7_2008_10)
summary(m_GA_bam_2009)
  #plot(m_GA_bam_2009, all.terms = TRUE,pages=1, shade = TRUE, shade.col = "lightblue")
  plot(m_GA_bam_2009, select=1, shade = TRUE, shade.col = "lightblue",  shift = coef(m_GA_bam_2009)[1]) #BW
  plot(m_GA_bam_2009, select=2, ylim=c(265, 280),shade = TRUE, shade.col = "lightblue",  shift = coef(m_GA_bam_2009)[1]) #mat age
  plot(m_GA_bam_2009, select=3, ylim=c(274, 278),shade = TRUE, shade.col = "lightblue",  shift = coef(m_GA_bam_2009)[1],  xlab  = "13 : 2008-01,  20: 2008-08,  30: 2009-06,  40: 2010-04,  50: 2011-02") #birth_Y_M_num
  plot(m_GA_bam_2009, select=4, ylim=c(272, 280),shade = TRUE, shade.col = "lightblue",  shift = coef(m_GA_bam_2009)[1]) #ssep

  gam.check(m_GA_bam_2009)
  concurvity(m_GA_bam_2009, full=TRUE)
  
  #estimate, 95%CI and d
  beta <- coef(m_GA_bam_2009)
  Vb <- vcov(m_GA_bam_2009, unconditional = TRUE)
  n <- 219790
  se <- sqrt(diag(Vb))
  d <- (abs(beta)/(sqrt(n)*se))
  my.ci <- data.frame(cbind(beta, lci = beta-1.96*se, uci = beta + 1.96*se, d))
  round(head(my.ci,14), 2)
```

## 2017-2020
```{r}
m_GA_bam_covid <- bam(GA_days ~ s(BW) +  s(mat_age) + s(birth_Y_M_num) + s(mean_ssep2) + parity_cat + sex + Urban3 + mother_nationality_cat2 + Language, data=bevn_eco_in7_2017_20)
summary(m_GA_bam_covid)
  #plot(m_GA_bam_covid, all.terms = TRUE,pages=1, shade = TRUE, shade.col = "lightblue")
  plot(m_GA_bam_covid, select=1, shade = TRUE, shade.col = "lightblue",  shift = coef(m_GA_bam_covid)[1]) #BW
  plot(m_GA_bam_covid, select=2, ylim=c(265, 280),shade = TRUE, shade.col = "lightblue",  shift = coef(m_GA_bam_covid)[1]) #mat age
  plot(m_GA_bam_covid, select=3, ylim=c(274, 278),shade = TRUE, shade.col = "lightblue",  shift = coef(m_GA_bam_covid)[1], xlab  = "120 : 2016-12,  130: 2017-10,  140: 2018-08,  150: 2019-06,  160: 2020-04") #birth_Y_M_num
  plot(m_GA_bam_covid, select=4, ylim=c(272, 280),shade = TRUE, shade.col = "lightblue",  shift = coef(m_GA_bam_covid)[1]) #ssep

  k.check(m_GA_bam_covid)
  concurvity(m_GA_bam_covid, full=TRUE)
  
  #estimate, 95%CI and d
  beta <- coef(m_GA_bam_covid)
  Vb <- vcov(m_GA_bam_covid, unconditional = TRUE)
  n <- 332752
  se <- sqrt(diag(Vb))
  d <- (abs(beta)/(sqrt(n)*se))
  my.ci <- data.frame(cbind(beta, lci = beta-1.96*se, uci = beta + 1.96*se, d))
  round(head(my.ci,14), 2)
```

# Pre-term birth
## 2007-2020

```{r}
m_PTB_bam<-bam(PTB~s(BW)+ s(mat_age) + s(birth_Y_M_num) + s(month) +s(mean_ssep2) + parity_cat + Urban3 + Language + mother_nationality_cat2,family="binomial", data=bevn_eco_in7)
  summary(m_PTB_bam)

    #adding intercept
#plot(m_PTB_bam, pages = 1, trans = plogis, shift = coef(m_PTB_bam)[1])
  plot(m_PTB_bam, trans = plogis, select=1,,shift = coef(m_PTB_bam)[1], shade = TRUE, shade.col = "lightblue") #BW
  plot(m_PTB_bam, trans = plogis, select=2, ylim=c(0, 0.05), shift = coef(m_PTB_bam)[1], shade = TRUE, shade.col = "lightblue") #matage
  plot(m_PTB_bam, trans = plogis, select=3, ylim=c(0.01, 0.02), shift = coef(m_PTB_bam)[1], shade = TRUE, shade.col = "lightblue",  xlab  = "1 : 2007-01,     25: 2009-01,      50: 2011-02,     75: 2013-03,      100: 2015-04,      125: 2017-05,      150: 2019-06") #birth_Y_M_num
  plot(m_PTB_bam, trans = plogis, select=4, ylim=c(0.012, 0.016), shift = coef(m_PTB_bam)[1], shade = TRUE, shade.col = "lightblue") #month
  plot(m_PTB_bam, trans = plogis, select=5, ylim=c(0.001, 0.02),shift = coef(m_PTB_bam)[1], shade = TRUE, shade.col = "lightblue") #ssep

  gam.check(m_PTB_bam) #some kindex values are a bit far from 1
  concurvity(m_PTB_bam)
  
  #to calculate the OR of PTB
  OR <- exp(coef(m_PTB_bam))
  beta <- coef(m_PTB_bam)
  Vb <- vcov(m_PTB_bam, unconditional = TRUE)
  se <- sqrt(diag(Vb))
  lci <- exp(beta-1.96*se)
  uci <- exp(beta+1.96*se)
  d <- abs(beta)/1.81
  my.ci <- data.frame(cbind(OR, lci, uci, d))
  round(head(my.ci, 13), 2)
  
  #without birthweight
  m_PTB_bam2<-bam(PTB~ s(mat_age) + s(birth_Y_M_num) + s(month) +s(mean_ssep2) + parity_cat + Urban3 + Language + mother_nationality_cat2,family="binomial", data=bevn_eco_in7)
  summary(m_PTB_bam2)
  gam.check(m_PTB_bam2)
  concurvity(m_PTB_bam2)
  
```

## 2008-2010
```{r}
m_PTB_bam_2009 <-bam(PTB~s(BW)+ s(mat_age) + s(birth_Y_M_num) + s(month) +s(mean_ssep2) + parity_cat + Urban3 + Language + mother_nationality_cat2,family="binomial", data=bevn_eco_in7_2008_10)
  summary(m_PTB_bam_2009)
  #plot(m_PTB_bam_2009, all.terms = TRUE,pages=1, shade = TRUE, shade.col = "lightblue")
  plot(m_PTB_bam_2009, trans = plogis, select=1, shade = TRUE, shade.col = "lightblue",  shift = coef(m_PTB_bam_2009)[1]) #BW
  plot(m_PTB_bam_2009, trans = plogis, select=2, ylim=c(0, 0.1),shade = TRUE, shade.col = "lightblue",  shift = coef(m_PTB_bam_2009)[1]) #mat age
  plot(m_PTB_bam_2009, trans = plogis, select=3, ylim=c(0, 0.2),shade = TRUE, shade.col = "lightblue",  shift = coef(m_PTB_bam_2009)[1],  xlab  = "13 : 2008-01,  20: 2008-08,  30: 2009-06,  40: 2010-04,  50: 2011-02") #birth_Y_M_num
  plot(m_PTB_bam_2009, trans = plogis, select=4, ylim=c(0, 0.1),shade = TRUE, shade.col = "lightblue",  shift = coef(m_PTB_bam_2009)[1]) #ssep
  
  #putting mean ssep and month and birth_Y_M_num as non-smooth variables
  m_PTB_bam_2009_2 <-bam(PTB~s(BW)+ s(mat_age) + birth_Y_M_num + month + mean_ssep2 + parity_cat + Urban3 + Language + mother_nationality_cat2,family="binomial", data=bevn_eco_in7_2008_10)
  summary(m_PTB_bam_2009_2)
  
  plot(m_PTB_bam_2009_2, trans = plogis, select=1, shade = TRUE, shade.col = "lightblue",  shift = coef(m_PTB_bam_2009_2)[1]) #BW
  plot(m_PTB_bam_2009_2, trans = plogis, select=2, ylim=c(0, 0.1),shade = TRUE, shade.col = "lightblue",  shift = coef(m_PTB_bam_2009_2)[1]) #mat age

  k.check(m_PTB_bam_2009_2)
  concurvity(m_PTB_bam_2009_2)
  
  #to calculate the OR of PTB
  OR <- exp(coef(m_PTB_bam_2009_2))
  beta <- coef(m_PTB_bam_2009_2)
  Vb <- vcov(m_PTB_bam_2009_2, unconditional = TRUE)
  se <- sqrt(diag(Vb))
  lci <- exp(beta-1.96*se)
  uci <- exp(beta+1.96*se)
  d <- abs(beta)/1.81
  my.ci <- data.frame(cbind(OR, lci, uci, d))
  round(head(my.ci, 16), 2)
```

## 2017-2020
```{r}
m_PTB_bam_covid <-bam(PTB~s(BW)+ s(mat_age) + s(birth_Y_M_num) + s(month) +s(mean_ssep2) + parity_cat + Urban3 + Language + mother_nationality_cat2,family="binomial", data=bevn_eco_in7_2017_20)
  summary(m_PTB_bam_covid)
  
#birth_Y_M, month and mean ssep as linear variables:
  m_PTB_bam_covid_2 <-bam(PTB~s(BW)+ s(mat_age) + birth_Y_M_num + month + mean_ssep2 + parity_cat + Urban3 + Language +  mother_nationality_cat2,family="binomial", data=bevn_eco_in7_2017_20)
  summary(m_PTB_bam_covid_2)

   plot(m_PTB_bam_covid_2, trans = plogis, select=1, shade = TRUE, shade.col = "lightblue",  shift = coef(m_PTB_bam_covid_2)[1]) #BW
  plot(m_PTB_bam_covid_2, trans = plogis, select=2, ylim=c(0, 0.05),shade = TRUE, shade.col = "lightblue",  shift = coef(m_PTB_bam_covid_2)[1]) #mat age

  k.check(m_PTB_bam_covid_2)
  concurvity(m_PTB_bam_covid_2)
  
  #to calculate the OR of PTB
  OR <- exp(coef(m_PTB_bam_covid_2))
  beta <- coef(m_PTB_bam_covid_2)
  Vb <- vcov(m_PTB_bam_covid_2, unconditional = TRUE)
  se <- sqrt(diag(Vb))
  lci <- exp(beta-1.96*se)
  uci <- exp(beta+1.96*se)
  d <- abs(beta)/1.81
  my.ci <- data.frame(cbind(OR, lci, uci, d))
  round(head(my.ci, 16), 2)
```